### ISSUE TITLE
No 'unmaskExpirationDate' in 'getCustomerPaymentProfileRequest'

### ISSUE THREAD

**Issue by brockpace** [AuthorizeNet/sdk-dotnet#112]
In the API you can send a request to unmask the Expiration date (https://developer.authorize.net/api/reference/index.html#homereq-get-customer-payment-profile).  Can unmaskExpirationDate get added as a boolean property?  This is very helpful for notifying customers when their card expiration date is about to expire.

**Comment by brianmc** [comment]
Latest release 1.8.8 has unmaskExpirationDate included.  
https://www.nuget.org/packages/AuthorizeNet/
https://github.com/AuthorizeNet/sdk-dotnet/releases/tag/1.8.8
