### ISSUE TITLE
No way to get paypal email

### ISSUE THREAD

**Issue by dimon82** [AuthorizeNet/sdk-dotnet#117]
Looking at this documentation http://developer.authorize.net/api/reference/index.html#paypal-express-checkout-get-details I see that it returns Email in secureAcceptance object. However, in .NET SDK there is no such field in AuthorizeNet.Api.Contracts.V1.transactionResponseSecureAcceptance class (https://github.com/AuthorizeNet/sdk-dotnet/blob/master/Authorize.NET/Api/Contracts/V1/AnetApiSchema.generated.cs#L2811).

Getting an email address of paypal customer is essential for our customer service.

**Comment by brianmc** [comment]
Hi @dimon82, We're looking at this one right now. 

Brian

**Comment by dimon82** [comment]
@brianmc thank you. Please let me know as soon as you have a solution. I'm in the middle of integration and the company wants to get paypal integrated as soon as possible. I'd appreciate if you could take a look at my other issues as well (118,119 and 120). This one and 118 are being the most important for me right now.

**Comment by brianmc** [comment]
Hi @dimon82, it looks like we are not returning the email and as you rightly say it's important response data for the merchant.  We're looking at how we can expedite an update to resolve this issue.  Unfortunately I have no timeframe for you right now, but I'll update you as soon as we have a better idea on that front.

We're also investigating your other issues, and thank-you again for bringing them to our attention.

Brian

**Comment by dimon82** [comment]
@brianmc thank you.

**Comment by dimon82** [comment]
hi @brianmc, any update on this and/or any other of my bugs?

**Comment by brianmc** [comment]
Hi @dimon82, we'll be getting this one and #118 into an upcoming release, I don't have an exact date right now but we'll keep this issue open and I will reply when we have a better date.

Thanks,  
Brian

**Comment by brianmc** [comment]
Hi @dimon82 Since we had to make these changes in the API that took some time and then we had just missed an SDK update so that took another while.  Overall a very poor response time but please rest assured we really appreciate your feedback and this issue plus the other two you raised have now been implemented and represented a significant improvement in our SDK.

Thank-you!
