### ISSUE TITLE
Incorrect amount is being charged for paypal transaction

### ISSUE THREAD

**Issue by dimon82** [AuthorizeNet/sdk-dotnet#118]
For PayPal: Amount that I set in authCaptureContinueTransaction transaction type is being ignored and instead the one from authCaptureTransaction request is charged.

Here is the scenario. I call authCaptureTransaction to initiate it, redirect user to paypal, he or she chooses shipping address and it goes back to my site to choose shipping method (which can be different based on shipping address that the customer chose). I then add a cost of shipping method to the order total and send it along with authCaptureContinueTransaction request which is what should be used as a final charge.

**Comment by brianmc** [comment]
Hi @dimon82 ,

Apologies for the delay in responding.  We have confirmed this as an issue.  We will be making the fix, I don't have an exact date for when the update will be released but it should be more like weeks not months.  I'll keep this issue open and let you know as we get closer to a release date.

Thanks again for all your feedback,

Brian

**Comment by dimon82** [comment]
Hi @brianmc are there any updates on my issues? It's been awhile and no word from you guys. How long do you think it's going to take you to fix and push them live?

**Comment by brianmc** [comment]
Hi @dimon82 See #117 for my apologies on delay in addressing your PayPal issues.  This was a vital update and we appreciate you reporting it.  It's fixed!  Let us know if the behavior is as expected now.

Thanks again,

Brian
