### ISSUE TITLE
Paypal transaction: customer's first name and last name are not in separate fields

### ISSUE THREAD

**Issue by dimon82** [AuthorizeNet/sdk-dotnet#119]
Calling "Get Details" for Paypal transaction returns first and last names in transactionResponse.shipTo.firstName field. Please use transactionResponse.shipTo.lastName field for customer's last name.

**Comment by brianmc** [comment]
Hi @dimon82,

This is not ideal I agree but unfortunately the PayPal API returns only one field for shipToName and so we were very reluctant to try to split it and potentially upset a merchants customer with an incorrect split.

https://developer.paypal.com/docs/classic/api/merchant/GetExpressCheckoutDetails_API_Operation_NVP/

![image](https://cloud.githubusercontent.com/assets/1022976/12267369/a6671158-b8fc-11e5-8112-c6dc72394aa4.png)

**Comment by brianmc** [comment]
BTW We should document that and we will get that updated at https://developer.authorize.net/api/reference/#paypal-express-checkout-get-details.

Thanks again for the great feedback.

**Comment by dimon82** [comment]
@brianmc thanks. No need to split it, I agree. But how about returning PayerName (PersonNameType) Fields for first and last names?
