### ISSUE TITLE
Paypal transactions: partial refunds

### ISSUE THREAD

**Issue by dimon82** [AuthorizeNet/sdk-dotnet#120]
It doesn't seem like there is a way to issue a partial refund for paypal transactions. There is no option to pass in an amount to refund (http://developer.authorize.net/api/reference/index.html#paypal-express-checkout-credit). It refunds an order in full currently.

Would it be possible to add this feature?

**Comment by brianmc** [comment]
Hi @dimon82,

Apologies again for the delay.  You can pass amount to the PayPal refund transaction request, we'll be updating the documentation to show that, here's the sample request in the meantime:

<createTransactionRequest xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd">
    <merchantAuthentication>
    <name>YOURS</name>
    <transactionKey>YOURS</transactionKey>
  </merchantAuthentication>
  <transactionRequest>
     <transactionType>refundTransaction</transactionType>
    <refTransId>138</refTransId>
    <amount>12</amount>
    </transactionRequest>
</createTransactionRequest>
