### ISSUE TITLE
Updating a Subscription errors out on unchanged subscription amount - C# API

### ISSUE THREAD

**Issue by 0lorak0** [AuthorizeNet/sdk-dotnet#122]
Hello, 
 
I am having trouble updating a subscription's expiration date and billing info.  These are the ONLY fields I need to update.  When I create my request using the C# API:
```
var subscriptionType = new ARBSubscriptionType
{
    billTo = addressInfo,
    payment = cc
};

var request = new ARBUpdateSubscriptionRequest
{
    subscription = subscriptionType, 
    subscriptionId = updateModel.AuthNetSubId.ToString()
};

var controller = new  ARBUpdateSubscriptionController(request);

controller.Execute();

var xml = AuthorizeNet.Util.XmlUtility.GetXml(request);

var response = controller.GetApiResponse();
```
I get the following error message via the controller's error messages: 
 
***Error: E00003 The 'AnetApi/xml/v1/schema/AnetApiSchema.xsd:amount' element is invalid - The value '0' is invalid according to its datatype 'Decimal' - The MinInclusive constraint failed.***
 
Even though I did NOT specify an amount, when I view the XML, I get the following:
```
<?xml version=\"1.0\" encoding=\"utf-8\"?>
<ARBUpdateSubscriptionRequest
    xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"
    xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\"
    xmlns=\"AnetApi/xml/v1/schema/AnetApiSchema.xsd\">
    <merchantAuthentication> 
        <name>ApiLoginId</name>
        <transactionKey>TransactionKey</transactionKey> 
    </merchantAuthentication>
    <subscriptionId>3044281</subscriptionId>
    <subscription>
        <amount>0</amount>   
        <trialAmount>0</trialAmount>  
        <payment>
            <creditCard>        
                <cardNumber>4111111111111111</cardNumber>    
                <expirationDate>1017</expirationDate>      
            </creditCard>
        </payment>    
        <billTo>      
            <firstName>SomeFirstName</firstName> 
            <lastName>SomeLastName</lastName>      
            <address>SomeAddress</address>      
            <city>SomeCity</city>      
            <zip>91234</zip>    
        </billTo>  
    </subscription>
</ARBUpdateSubscriptionRequest>
```
As you can see, even though I did not specify an amount or trial amount, they are still showing up in the XML.  I even tried setting:
```
request.subscription.amountSpecified = false;
request.subscription.trialAmountSpecified = false;
```
It was my understanding, via reading the documentation and posts on Authorize.Net forums, that during a subscription update, one only needed to include the fields that were changing.  Is this no longer the case?  Or am I doing something else incorrectly that's causing the error message above?

If I examine the request object BEFORE the controller.Execute() line, the amountSpecified and trialAmountSpecified are both false.  They both change to true once the controller.Execute() line is run.

I looked through the master branch and I *think* I found the issue, starting at:
[ARBUpdateSubscriptionController](https://github.com/AuthorizeNet/sdk-dotnet/blob/master/Authorize.NET/Api/Controllers/ARBUpdateSubscriptionController.cs) - BeforeExecute().  

BeforeExecute calls [RequestFactoryWithSpecified](https://github.com/AuthorizeNet/sdk-dotnet/blob/master/Authorize.NET/Api/Contracts/V1/RequestFactoryWithSpecified.cs).ARBUpdateSubscriptionRequest, which calls:

```
        public static void ARBSubscriptionType(ARBSubscriptionType argument)
        {
            if (null != argument)
            {
                paymentScheduleType(argument.paymentSchedule);
                if (0 <= argument.amount) { argument.amountSpecified = true; }
                if (0 <= argument.trialAmount) { argument.trialAmountSpecified = true; }
                paymentType(argument.payment);
                orderType(argument.order);
                customerType(argument.customer);
                nameAndAddressType(argument.billTo);
                nameAndAddressType(argument.shipTo);
            }
        }
```

So it looks like if the subscription amount or trial amount is not specified, it automatically sets the amountSpecified and trialAmountSpecified fields to true.  But this goes against the documentation I have read that if we are not updating a field, then we don't need to include it.  

I noticed that the ARBSubscriptionType method is also called during ARBCreateSubscriptionRequest.  Maybe this is why the method above is written the way it is.  

I would think that it might be useful to check, during an update, if the amountSpecified and trialAmountSpecified is already set to false, then not to set them to true if the amount and trialAmount are <= 0.

**Comment by sunnyrajrathod** [comment]
Hi @0lorak0 ,
We have fixed this issue in our recent release.
Please note that while updating the subscription, specifying request.subscription.trialAmountSpecified value is mandatory now, so that XML is correctly generated.
Thanks.
