### ISSUE TITLE
Order.AddLineItem doesn't add the description

### ISSUE THREAD

**Issue by ingersoj** [AuthorizeNet/sdk-dotnet#123]
When calling the Order.AddLineItem method, the description string parameter value doesn't get copied to the line item description as it should.  Instead, the order's description is copied to every line item.

**Comment by ingersoj** [comment]
I just saw that user mlunn01 created a pull request (#121) that fixes this issue.  Can someone please merge this into the master project?

**Comment by brianmc** [comment]
We'll get this merged in for the next release.  Thanks.

**Comment by brianmc** [comment]
Fixed in the latest release, thank-you for the PR @ingersoj
