### ISSUE TITLE
GatewayCustomer.AddCreditCard() does not return duplicate PaymentProfileId

### ISSUE THREAD

**Issue by danielsd** [AuthorizeNet/sdk-dotnet#125]
The Authorize.Net API returns the PaymentProfileId of the existing credit card when attempting to add a duplicate but the .NET SDK has not been updated to make this available. The SDK still errors with the generic message: "Error processing request: E00039 - A duplicate customer payment profile already exists.".

Please add support for retrieving the existing payment profile id. It would also be nice if the existing customer profile id was made available when adding a duplicate customer. Currently it must be parsed out of the error message.

One way to keep returning the existing id's simple, consistent, and backwards compatible would be to make use of Exception.Data().

**Comment by brianmc** [comment]
Hi Daniel,

One of the reasons we moved to the new controller model in the SDKs was to allow us to reflect API features "almost immediately" in the SDK.  If you look at our new sample code for adding a payment profile you can see an example of the new controller model : https://github.com/AuthorizeNet/sample-code-csharp/blob/master/CustomerProfiles/CreateCustomerPaymentProfile.cs 

I just updated this sample to show how to retrieve the duplicate profile ID.

I understand you want this change in the old model code but we would love to get your feedback on using/switching to the new model.  Here's some more background on why we made the change: https://community.developer.authorize.net/t5/The-Authorize-Net-Developer-Blog/Why-a-New-Controller-Model/ba-p/52589

Thanks again for submitting this issue.

**Comment by brianmc** [comment]
I'm going to close this issue.  Please feel free to submit a pull request if you would like to keep using the old model.

Thanks again,

Brian
