### ISSUE TITLE
Invalid CC numbers are not causing Production to fail.

### ISSUE THREAD

**Issue by patrick-lake** [AuthorizeNet/sdk-dotnet#141]
Using version 1.8.9

We're using invalid CC numbers (some examples 4111111111111111 and 4209765612950187) with random date and CVV on a production environment (AuthorizeNet.Environment.PRODUCTION). We're getting the "Ok" resultCode back from Authorize.Net.

This is obviously not ideal since the user could make a typo entering the CC and AuthorizeNet is saying the payment was successful.

**Comment by sunnyrajrathod** [comment]
Hi,
What is the response code in transactionResponse? The transaction is approved only if the response code is **1**, it will be **2** for declined. 
For payment transactions, apart from resultCode, you can also check the errorCode and errorText in transactionResponse field for any errors.
Please let us know in case there are no errors in transactionResponse, and whether response code is **"1"**.

**Comment by brianmc** [comment]
Hi @patrick-lake just closing this one out but as Sunny said the main API response code is essentially an indication of did the API call succeed.  If it did then you need to look into the transaction response to actually find out if the financial transaction was successful.  You can see an example here : https://github.com/AuthorizeNet/sample-code-csharp/blob/master/PaymentTransactions/ChargeCreditCard.cs

I will say this is not entirely consistent across our API so I can understand the confusion, look out for our next generation of APIs where we'll definitely be addressing these types of inconsistencies.
