### ISSUE TITLE
invalid CC returns null with createCustomerProfileRequest

### ISSUE THREAD

**Issue by CatLover91** [AuthorizeNet/sdk-dotnet#142]
I am using `createCustomerProfileController` to create a CIM, and I am passing in a nonsensical credit card in order to catch error codes so they can be handled more gracefully. When I pass in the card info, the `GetApiResponse` method returns `null`. From what I gather, this should never happen.

Here is a rough outline of the code I am trying to run:

```
var request = new updateCustomerPaymentProfileRequest
{
    customerProfileId = cimId,
    paymentProfile = new customerPaymentProfileExType
    {
        billTo = new customerAddressType
        {
            address = "sadjlksad",
            city = "saddas",
            country = "United States",
            firstName = "fdsasfa",
            lastName = null,
            state = "South Carolina",
            zip = "123312"
        },
        customerPaymentProfileId = GetCustomerPaymentProfile(cimId),
        payment = new paymentType
        {
            Item = new creditCardType
            {
                cardNumber = "213423414",
                cardCode = "34121234",
                expirationDate = "2019-15"
            }
        }
    },
    validationMode = validationModeEnum.liveMode
};

var controller = new updateCustomerPaymentProfileController(request);
controller.Execute();

var response = controller.GetApiResponse();
```

in this case, `response == null` when I am expecting `response.messages.resultCode == messageTypeEnum.Error`

**Comment by ramittal** [comment]
If the controller is returning null for ApiResponse, you would be able to query the ErrorResponse (using GetErrorResponse()) and get all the details on the errors that include error code and descriptions. Hope this is what you are looking for.

**Comment by CatLover91** [comment]
@ramittal: your comment was very helpful and solved my issue! It still makes me wonder why `GetErrorResponse()` is needed, would it not be wiser to throw an error code with `GetApiResponse()` similar to how expired credit cards are handled?

**Comment by brianmc** [comment]
Hi @CatLover91 , just closing out this issue but your feedback totally makes sense and we're looking at ways to make the responses consistent across the error range and indeed with the language style guides.

**Comment by simeyla** [comment]
@brianmc  at the very least you need to update your sample code to account for this. 
It is VERY misleading. For instance this is the code (today) for createCustomerPaymentProfile:

It tries to account for `response` being null, but in the else clause it actually uses `response`. This code just flat out doesn't work in the context of the OP's question. It doesn't use GetErrorResponse() at all. There needs to be another `else if`.

            //Prepare Request
            var controller = new createCustomerPaymentProfileController(request);
            controller.Execute();

             //Send Request to EndPoint
            createCustomerPaymentProfileResponse response = controller.GetApiResponse(); 
            if (response != null && response.messages.resultCode == messageTypeEnum.Ok)
            {
                if (response != null && response.messages.message != null)
                {
                    Console.WriteLine("Success, createCustomerPaymentProfileID : " + response.customerPaymentProfileId);
                }
            }
            else
            {
                Console.WriteLine("Error: " + response.messages.message[0].code + "  " + response.messages.message[0].text);
                if (response.messages.message[0].code == "E00039")
                {
                    Console.WriteLine("Duplicate ID: " + response.customerPaymentProfileId);
                }
            }

            return response;

**Comment by simeyla** [comment]
Also note in this particular case the error is technically due to bad XML and not a bad request.

This particular error can be avoided by limiting the length of `cardCode` that you send to a max of 4 digits.

E00003: `The 'AnetApi/xml/v1/schema/AnetApiSchema.xsd:cardCode' element is invalid - The value XXXXXXXXXX is invalid according to its datatype 'AnetApi/xml/v1/schema/AnetApiSchema.xsd:cardCode' - The actual length is greater than the MaxLength value.`

**Comment by adavidw** [comment]
Hi @simeyla,

I think the response parsing code needs cleaning up for _all_ the samples, but in the short term, I've gone ahead and made some changes to createCustomerPaymentProfile that should make things clearer. Let me know if I've missed anything.
