### ISSUE TITLE
Create ChangeLog.md or use Releases tab to track changes

### ISSUE THREAD

**Issue by sgwatgit** [AuthorizeNet/sdk-dotnet#143]
On many repositories when I want to see what changed between versions I can either look at a changelog markdown file in the root of the repository or I can look at the releases tab in Github.

Examples [npm with releases tab](https://github.com/npm/npm/releases), [angular.js with changelog.md](https://github.com/angular/angular/blob/master/CHANGELOG.md).

Is there already something like this for the repo and I just overlooked it? If not I think this would be a helpful addition.

Thanks

**Comment by sunnyrajrathod** [comment]
API changes can be tracked here - http://developer.authorize.net/api/changes/. SDKs are also updated on API changes.
Also, for any new release, this [blog](https://community.developer.authorize.net/t5/The-Authorize-Net-Developer-Blog/bg-p/DeveloperBlog) is updated.
Going forward, we will update the Releases tab as well.
