### ISSUE TITLE
Silent Post/Webhook Detailed Documentation of Events

### ISSUE THREAD

**Issue by brentdavid2008** [AuthorizeNet/sdk-dotnet#147]
Hi,
Our team is implementing your payment gateway into one of our clients apps and had a few questions about subscriptions/webhooks and events...

Is there any documentation for something like webhooks that you guys provide?  I'm looking for a detailed list of events that get posted to some particular URL and the payloads that go with.  I am new to this platform so i'm unsure of how you guys handle it.

Specifically, i need to know when a subscription payment failed, succeeded, gets canceled, etc. and even one time payments succeed or fail, and how to know the difference between the two.

I've looked through your c# example code but i don't seem to find anything in there relating to webhooks or events that get posted to another URL to notify of something happening.

I did see that you have merchant notifications, but i'm not sure why they're only emails.

Forgive me if they are listed somewhere, but I have not yet come across them in my searching efforts.

Thanks,
Brent

**Comment by bilderbach** [comment]
Hey Brent, 

Problem we have see with postback is you may miss a transaction...we found the reporting API to be a better approach in the end.
http://developer.authorize.net/api/reference/#transaction-reporting

Hope that helps!

-R

**Comment by brianmc** [comment]
Hi @brentdavid2008 & @bilderbach ,

We'll be launching new webhooks functionality very soon, please email developer@authorize.net and mention our webhooks beta (plus my name Brian) if you'd like more information.  We will be including subscription and transaction events (with more to come) and we will be providing a reliable (ie we'll try til you get it) messaging system to deliver these events.

As Robert suggested our reporting API will always give comprehensive reporting of transaction history, including subscription based transactions.

Thanks,

Brian

**Comment by brentdavid2008** [comment]
@bilderbach and @brianmc 
Curious as to how i'd "miss" a transaction.  We are really just using the API for one time payments, the concern is with bank accounts, they may not settle for 3-5 days.  Transaction reporting and polling the api for it to be settled seems odd.  What scenarios are you saying i'd 'miss' something and why?

I did email for beta documentation.
Thanks,
Brent

**Comment by bilderbach** [comment]
Brent, problems we have come across missing transactions is based on server
availability or internet congestion, we quickly found out we were not
receiving all the transactions and ended up checking them with the
reporting API.

Brian, another issue we have had to overcome is the Settled_Submitted_Date
does not get passed in the postback, so we are always working off a sliding
window based on when we receive the postback...would be great if it was
passed as a field.

Thanks!

**Comment by brentdavid2008** [comment]
I see.  So the beta that was talking about should be very helpful since it sounds like it'll try until it gets a successful 200 response code.  

@brianmc When's a projected release time-frame for something like that?  I'd hate to write code that pulls the server or even the silent post data that you have now, just to have it change in a week or so (assuming it's that soon)

Thanks,
Brent
