### ISSUE TITLE
Cannot retrieve a card type after creation of CIM Payment Profile

### ISSUE THREAD

**Issue by sgwatgit** [AuthorizeNet/sdk-dotnet#148]
This thread has additional information about this general request https://community.developer.authorize.net/t5/Integration-and-Testing/Retrieve-Credit-Card-Type-of-Payment-Profile-using-CIM/td-p/4585/page/2

Basically there isn't a way to get a credit card type without either

1. Creating a new payment profile
2. Making a transaction with a payment profile

If I want to not perform any transactions but instead save the payment option that a user selects for later (documentation, invoicing) I cannot show them which card type they had selected without keeping a link between their paymentprofile id and the card type from when the create/update the profile in my system.

If we get the expiration date and last 4 digits, why can't the api send back the card type?

It would be great if this were available in the getCustomerPaymentProfileResponse but I'd be happy if it was available in the update or validate responses.  All 3 would be ideal.

Thanks

**Comment by brianmc** [comment]
Hi @sgwatgit, this feature should absolutely have been in our Customer API from the start.  The good news is we're implementing the functionality right now and it should be available in an upcoming release.  While I can't give you definitive dates I can say we'really talking about weeks away, not months or years.

Thanks for the feedback,

Brian

**Comment by sgwatgit** [comment]
@brianmc Thanks for the update.

When the functionality is released will the card type also appear for all payment profiles in requests to get a Customer Profile? We make this request to display payment profile options to customers during checkout in our ecommerce solutions.

**Comment by brianmc** [comment]
Yes, card type will be returned on GetCustomerProfile and GetCutomerPaymentProfile calls.
