### ISSUE TITLE
GatewayResponse.ToString() returns empty string

### ISSUE THREAD

**Issue by thoseamongus** [AuthorizeNet/sdk-dotnet#149]
ResponseBase.APIResponseKeys returns a new Dictionary on every request so that when GatewayResponse.LoadKeys() is called the dictionary is only populated in that one instance so when you call GatewayResponse.ToString() returns and empty string. Since the instance of the dictionary is new on each request.

So an easy fix is to 

make a constructor like 

protected ResponseBase()
{
 APIResponseKeys = new Dictionary<int,string>();
}
and change the property to be like this

protected Dictionary<int,string> APIResponseKeys = {get;private set;}

**Comment by sapta89** [comment]
@thoseamongus you're right that each access to APIResponseKeys will return a blank dictionary so overriding ToString() will have no keys to iterate on. But writing a constructor to an abstract class may not be a good design case. We'll be fixing this issue in the next release.

**Comment by brianmc** [comment]
Thank you for the issue report & for contributing to our SDK.  This sissue has been fixed in the latest release.
