### ISSUE TITLE
invalid child element 'employeeId'?

### ISSUE THREAD

**Issue by LoyalServant** [AuthorizeNet/sdk-dotnet#154]
The schema (AnetApiSchema.generated.cs) has a string 'EmployeeId' that they appear to have removed.
I started getting an error reported by users from the gateway this morning (8/23) and once I stopped setting this property the issue went away.
The affected class is transactionRequestType

Just putting this here in case anyone else gets bitten by it!
Unfortunately my familiarity with this is minimal so I have no idea if this is a good permanent fix.

**Comment by DonWMason** [comment]
I ran into this this morning as well.

**Comment by Sapbasu15** [comment]
This issues is resolved. Please verify that 'EmployeeId' field is usable now.
