### ISSUE TITLE
Order.AddLineItem still doesn't add the description

### ISSUE THREAD

**Issue by ingersoj** [AuthorizeNet/sdk-dotnet#155]
This issue was supposedly fixed with item #123, but the fix doesn't work as intended.  The line item description now only gets added if it's empty.  If you try to add a line item description that isn't an empty string, the order's description is still used.

**Comment by akankaria** [comment]
Hi @ingersoj,

Sorry for missing this out. We have made a fix in #156. We plan to release an SDK update shortly.
Will keep you posted.

**Comment by gnongsie** [comment]
This has been released as part of v1.9.6. I'll be closing this issue now.
