### ISSUE TITLE
ExecuteWithApiResponse returns null

### ISSUE THREAD

**Issue by brianharwell** [AuthorizeNet/sdk-dotnet#157]
I forgot to specify the transactionType of the transaction request and the response from the controller was null. Luckily I could see some debug information in the diagnostic tools so I could see that I was receiving a response. There was indeed an error so I would think _something_ should be returned rather than null.

E00003:The element 'transactionRequest' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd' has invalid child element 'amount' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd'. List of possible elements expected: 'transactionType' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd'.

**Comment by chsriniv9** [comment]
@brianharwell 

Below steps show how to get the errorresponse when response is null.

**Step 1:** instantiate the controller that will call the service
```                                                
       var controller = new createTransactionController(request);
       controller.Execute();
```

**Step 2:** get the response from the service (errors contained if any)
```            
        var response = controller.GetApiResponse();
```

**Step 3:** validate response 
```            
        if (response != null)
        {
            // Your code goes here
        }
```
                                                
**Step 4:** If Response is null, then in else part, call the GetErrorResponse() method as shown below to get the error messages/response.
```
       else
       {
           // Check for errors
           ANetApiResponse errorResponse = controller.GetErrorResponse();
           if (errorResponse.messages.message.Length > 0)
           {
               Console.WriteLine("Controller_Name Creation Failed.");
               Console.WriteLine("Error Code: " + errorResponse.messages.message[0].code);
               Console.WriteLine("Error message: " + errorResponse.messages.message[0].text);
           }
           else
           {
               Console.WriteLine("Null Response.");
           }
       }
```

**Comment by chsriniv9** [comment]
Closing this based on the steps provided previously. Please feel free to re-open if further support needed on this issue.
