### ISSUE TITLE
SIMResponse Validate Method?

### ISSUE THREAD

**Issue by ejwettstein** [AuthorizeNet/sdk-dotnet#158]
Since the the Validate method has been removed from the SIMResponse, how do actually check whether the post message came from Authorize.Net?

**Comment by akankaria** [comment]
Hi @ejwettstein,
Thanks for raising this issue. We have restored the validate method to validate the SIM response (#156). This change will be available with our next SDK release.

**Comment by gnongsie** [comment]
This has been released as part of v1.9.6. I'll be closing this issue now.
