### ISSUE TITLE
Update payment profile address only

### ISSUE THREAD

**Issue by chrisklepeis** [AuthorizeNet/sdk-dotnet#159]
How would I update just the payment profile address, without having to retrieve the credit card information from the customer again?

I've tried retrieving the profile from from API and plugging that into updateCustomerPaymentProfileRequest, but without an example or an answer of whether or not its supported, its very difficult to figure out.

**Comment by sgwatgit** [comment]
```csharp
var creditCard = new creditCardType
{
	cardNumber = creditCard.CardNumber,
	expirationDate = creditCard.GetExpirationString(),
	cardCode = creditCard.CardSecurityCode,
};

var paymentType = new paymentType { Item = creditCard };

var billingAddr = new customerAddressType()
{
	company = customerAddress.Company,
	firstName = customerAddress.FirstName,
	lastName = customerAddress.LastName,
	address = customerAddress.Street,
	city = customerAddress.City,
	state = customerAddress.State,
	zip = customerAddress.Zip,
	country = customerAddress.Country,
	phoneNumber = customerAddress.Phone,
	faxNumber = customerAddress.Fax
};

var paymentProfile = new customerPaymentProfileExType
{
	billTo = billingAddr,
	payment = paymentType,
	customerPaymentProfileId = request.PaymentProfile.ID
};

var updatePaymentProfileRequest = new updateCustomerPaymentProfileRequest()
{
	customerProfileId = request.ProfileID,
	paymentProfile = paymentProfile,
	validationMode = validationMode
};

var controller = new updateCustomerPaymentProfileController(updatePaymentProfileRequest );
controller.Execute();

var response = controller.GetApiResponse();
```

Obviously there is a lot missing here, the source values/fields will need to be provided by you, but this is generally the idea.

**Comment by chrisklepeis** [comment]
@sgwatgit In your example, the credit card information has to be provided... but in our case if we simply want to just update the billing address, without asking the customer for that information again, I'm not sure how to do it.... right now, using the test environment I'm loading the existing payment profile like so:

            var getPmtProfileController = new getCustomerPaymentProfileController(
                new getCustomerPaymentProfileRequest()
                {
                    customerProfileId = profileId,
                    customerPaymentProfileId = paymentProfileId
                    //request.unmaskExpirationDateSpecified = true;
                    // unmaskExpirationDate = true
                });
            getPmtProfileController.Execute();

            var response = getPmtProfileController.GetApiResponse();
            var ccInfo = paymentProfileResponse.paymentProfile.payment.Item as creditCardMaskedType;

            // Is the CVV lost?

            var updateProfileRequest = new updateCustomerPaymentProfileRequest()
            {
                customerProfileId = profileId,
                paymentProfile = new customerPaymentProfileExType()
                {
                    billTo = billingAddress.ToAuthNetAddressType(),
                    customerPaymentProfileId = paymentProfileId,
                    payment = new paymentType()
                    {
                        Item = new creditCardType()
                        {
                            cardNumber = ccInfo.cardNumber,
                            expirationDate = ccInfo.expirationDate
                        }
                    }
                },
                validationMode = validationModeEnum.none
            };

            // instantiate the controller that will call the service
            var updatePmtProfilecontroller = new updateCustomerPaymentProfileController(updateProfileRequest);
            updatePmtProfilecontroller.Execute();
            var response2 = updatePmtProfilecontroller.GetApiResponse().


I recall reading somewhere that the API allows sending through masked data... any perhaps somehow it can detect that there were no changes to the credit card since I am passing in the masked data?

At least in the dev environment the above example appears to work... just don't want any surprises when going live.

**Comment by sgwatgit** [comment]
@chrisklepeis Ahh right. I misread your question.

This is how we are doing it and have not run into any issues in production.

```
// First get the original profile information
var profileRequest = new getCustomerPaymentProfileRequest()
{
	customerProfileId = request.ProfileID,
	customerPaymentProfileId = request.PaymentProfileID,
	unmaskExpirationDate = true,
	unmaskExpirationDateSpecified = true
};

var getController = new getCustomerPaymentProfileController(profileRequest);
getController.Execute();

var profileResponse = getController.GetApiResponse();

// Use the masked credit card info and the current request's updated billing info to create a new update request
var maskedCard = (creditCardMaskedType)profileResponse.paymentProfile.payment.Item;

var card = new creditCardType()
{
	cardNumber = maskedCard.cardNumber,
	expirationDate = maskedCard.expirationDate
};

var paymentType = new paymentType { Item = card };

var paymentProfile = new customerPaymentProfileExType
{
	billTo = new customerAddressType()
	{
		company = customerAddress.Company,
		firstName = customerAddress.FirstName,
		lastName = customerAddress.LastName,
		address = customerAddress.Street,
		city = customerAddress.City,
		state = customerAddress.State,
		zip = customerAddress.Zip,
		country = customerAddress.Country,
		phoneNumber = customerAddress.Phone,
		faxNumber = customerAddress.Fax
	},
	payment = paymentType,
	customerPaymentProfileId = request.PaymentProfileID
};

var authRequest = new updateCustomerPaymentProfileRequest()
{
	customerProfileId = request.ProfileID,
	paymentProfile = paymentProfile,
	validationMode = validationMode
};

var updateController = new updateCustomerPaymentProfileController(authRequest);
updateController.Execute();

var updateResponse = updateController.GetApiResponse();
```

Where `request` is a class instance we create and pass down into our code that wraps the SDK lib.
There's some copy-pasta (took out some extension method calls and other internal stuff) going on here so I hope it makes sense.

**Comment by chrisklepeis** [comment]
@sgwatgit  Thanks... looks about the same as what I have. Thanks for confirming. Would be helpful if the examples had something like this in there.

**Comment by brianmc** [comment]
Updated the sample here:  https://github.com/AuthorizeNet/sample-code-csharp/blob/master/CustomerProfiles/UpdateCustomerPaymentProfile.cs

**Comment by brianmc** [comment]
We definitely don't make that clear enough in the samples or docs, thanks @sgwatgit for helping with your sample.  I've update the pertinent sample code for a start.
