### ISSUE TITLE
ARB with General Error

### ISSUE THREAD

**Issue by bilderbach** [AuthorizeNet/sdk-dotnet#161]
We have been using your Reporting API for a couple year to verify our ARB subscription transactions are successful and updating them in our local database.

When a subscription is cancelled due to failures, we can see the failure with the API and I can see the ARB status shows cancelled after multiple failures and make those changes in our local database.

Everything seems to still be working fine for CC transactions.

A while back we added eCheck and the ARB failures are VERY messy!

If there is an ARB eCheck failure, its listed as a "General Error" with no transactionid, so it not available in the reporting API, and when we check the Subscription API its still showing as an active subscription.

So the problem is when a eCheck fails, we have no way with the API to figure out if the transaction is  successful or failed, only that we expected one to be processed today and there is no transaction information available online.

**Is there some workaround I can use to get the status of an eCheck ARB that's failed?**

Here is a sample subscription number you can lookup: 26812977

Let me know and I can send you any other info you might need.

Thanks for you help!
-R

**Comment by ashtru** [comment]
When you say 'ARB eChek failure'? Is it the response of an API call, or just that the scheduled monthly payment for an e-check subscription was declined? It will be assist in verifying the issue exists.

One workaround, I can suggest is to use GetSusbcription API, which gives the customerPaymentProfileId in response, and ValidateCustomerPaymentProfile API to see if the echeck is declined. If so, call CancelSubscription API to manually cancel the subscription.

Please describe the process you are using to combine Reporting API with subscription, specifically, which individual APIs and their order. And the frequency, is this done daily?
_Do you get GetSettledBatchList, use it to get transactions on that day, then use GetTransactionDetails, filter with recurringBilling=true, and then use subscription.id in the response for further verification in GetSubscriptionStatus API?_
