### ISSUE TITLE
.NET Core

### ISSUE THREAD

**Issue by adamreed90** [AuthorizeNet/sdk-dotnet#162]
Do you know if this can be used with .NET Core, and if not when you intend to release an update library for it?

**Comment by Serjster** [comment]
Yes, please!

**Comment by mitchcapper** [comment]
I agree, we have migrated a large amount of our code over but we cannot move the authorize.net segment due to the lack of .net core support.

**Comment by Serjster** [comment]
Sadly, you have to manually create all of the DTO and make the Rest calls yourself. Here' a bit more on SO: http://stackoverflow.com/q/40356667/550975

**Comment by brianmc** [comment]
Hi guys, I just ran the portability analyzer on our SDK and it's showing 97%, so not much to do, really just the http request classes and couple of others.  We'd really like to get a cut out soon, but with minimal impact to the .net framework compatibility obviously.  I can't promise anything but our plan right now is to create a new core branch, make the changes there and hopefully publish a separate beta core package until we have better testing and confidence around the overall compat.

Thanks for the request, it's exciting period for Microsoft and I'm loving .Net Core on the Mac :-)

Brian

**Comment by Insomniak47** [comment]
Are there any updates WRT timelines for core support?

**Comment by gehnster** [comment]
I'd also like an update. Thanks!

**Comment by Optiknights** [comment]
Any updates to the dotnet core updates? 
Until thats completed, does anyone have a walk through solution to integrating this as a .Net Nuget package targeting .Net framework on a dotnet core project? Or some other solution to get this package working on a dotnet core app?

**Comment by mitchcapper** [comment]
The package needs to be recreated to target .NET standard not .net framework.  .NET standard works for .NET core and .NET framework projects.    This framework is really just a wrapper around REST calls to the authorize.net server so if you were on a crunch you could just re-implement or migrate what code you could using their REST documentation.    Assuming Authorize.NET releases the SDK on nuget as a .NET standard library it will work in any VS instance including 2017.  Even if they didn't and they left it as an xproj converting to csproj is very easy so would not be an issue.  csproj files are not as back compat either which causes another problem.

**Comment by mtinnes** [comment]
Another vote for a quick convert to .net core. We are in a holding pattern until the core library is released and I hate to go through the trouble of converting it ourselves if a release is imminent.

**Comment by chassq** [comment]
Yes, please do this! NET Core 2.0 is almost here. Would be nice to roll this out with 2.0.

**Comment by chris-oswald** [comment]
+1 for .Net Core Support

**Comment by gehnster** [comment]
Would much like .NET Core support.

**Comment by vishalmgiri** [comment]
Team any update on .net core support

**Comment by brianmc** [comment]
Hi everyone.  We hear ya and thanks for all the feedback.  So had a crack at this earlier in the year and ran into a few roadblocks.  So at that point, knowing we have some great new lightweight client libraries coming we figured we would design those to be core from the ground up.  Obviously those are not out yet either so we owe an apology there.  What we will do right now is look at the last attempt again and review the issues.  Maybe we even open that core repo up as public and see if we can get some contributions.  Look for another update on this early next week.

**Comment by vishalmgiri** [comment]
Thanks for update Brain

**Comment by mitchcapper** [comment]
@brianmc can you go into more detail about what roadblocks you ran into with porting to .net core? As largely a http request wrapper it would seem moving to httpclient with the requests would work for all platforms without a lot of hassle.

**Comment by jasongaylord** [comment]
@brianmc Any update? Wouldn't mind contributing.

**Comment by jasongaylord** [comment]
@brianmc We couldn't wait so we created a very thin client using .NET Standard 2 mainly for very basic credit card charges. Haven't implemented tests yet, but It can be found at [https://github.com/biBERK/AuthorizeNet-dotnetcore](https://github.com/biBERK/AuthorizeNet-dotnetcore)

**Comment by mathewrg** [comment]
@brianmc, request you to provide an update w.r.t timelines. Thanks.

**Comment by martb1n** [comment]
@brianmc any updates for estimations? we are migrating out API to .NET.Core. AuthorizeNet is blocker for us? Any chances to get pre-release SDK earlier?
Thanks.

**Comment by chsriniv9** [comment]
Team,

ANET .Net Core SDK Beta Release is available in the [repo](https://github.com/AuthorizeNet/dotnet-core-sdk-beta). The beta release took longer than anticipated, apologies for the delay. Please use this release and provide if there are any feedback.

Thanks again for your patience and support !!

**Comment by fizch** [comment]
Is there any particular reason that you chose Core instead of Standard? The standard library will allow you to reuse the same code for Core and Framework projects. As it stands, now you have to maintain two versions of the project to support that.

**Comment by FredBell** [comment]
Same question here - 

What is the reason for not having a single AuthorizeNet library based on netstandard?
Simply port this library to netstandard and be done. 
There is no need to have multiple implementation of the library and in fact this will likely be dangerous moving forward as the compatibility between the two could be difficult to maintain moving forward.

If netstandard1.3 was an issue then use netstandard 2.0 - I ported myself many libraries from framework to netstandard and most took only a few hours to port.

Please respond to this thread as many of us are blocked by the authorizeNet library in our projects.

We would really appreciate some information from the team on this.

Thank you,

**Comment by nsmithdev** [comment]
I'm already using it as netstandard 2.0 just checked out the project chaged the target and compiled it local.  We only use a few methods but no problems so far.

**Comment by FredBell** [comment]
Nathan - 

Thank you very much for that information. 

I am currently using Authorize.Net as a gateway on a few .net websites. 
We are very familiar with Auth.net and appreciate its services, but I am also quite concerned that auth.net does not seem to have much software development capabilities when it comes to their API. 
It is a bit frightening to me to see that they do not have a netstandard library already available.
It is even more frightening to see that they did some work on creating one for netcore which has been in beta for many months). Why would they create a library using netcore? It does not make any sense at all and it looks like they do not understand the .net technology stack and how to use it. I am truly baffled by the lack of quality regarding this API.

A company of that size - specially in such a serious space as payment processing - should have this nailed a long time ago for sure. But no, so far they have no solution to this and they have not yet publicly communicated on when will they will release a netstandard library - if at all.

You would think that simply as a mark of respect for their many customers, auth.net would be more transparent regarding such an oversight on their part.

I just don't understand... don't know what else to say... it's nuts.

**Comment by chsriniv9** [comment]
Hi @fizch @FredBell @nsmithdev 
Thank you all for your inputs, kind words and continuous support.  This is significantly helping us to prioritize and steer Authorize.Net to deliver incremental value to our developers community and Merchants.

.Net Standard work is in our backlog and will update soon on the timelines !!

Thanks for your patience

**Comment by kfallstrom** [comment]
@chsriniv9 Please update this or the other ticket with some delivery / backlog updates...many of us would like to continue to use auth.net and if there is no movement here, we'll have no choice but to change vendors.

**Comment by natelaff** [comment]
About to dump authnet for this and many other reasons honestly. Need this to happen ASAP.

**Comment by adamreed90** [comment]
Indeed.

**Comment by hunkydoryrepair** [comment]
Yet another year has gone by and not on .NET Standard? 
This means it cannot be used with ASP.net Core websites at all. The task is probably less than a day to do. 
Be sure to target .NET Standard 2.0, not 2.1, so that it can still be used by any .NET Framework project.

**Comment by natelaff** [comment]
It's clear they don't care. They've had 6 years to support .NET Core/Standard. There is zero reason a .NET standard library couldn't have been done in this time. You only have to look as far as their outdated website to see they just have zero interest in developing in the technology, they just want the money.

**Comment by JocPelletier** [comment]
Why is this closed! @chsriniv9 your NET Core version is still beta and never beed updated!! There is a pull request supporting NET Standard: https://github.com/AuthorizeNet/sdk-dotnet/pull/291

**Comment by lyonb96** [comment]
So - the only option is an abandoned beta from several years ago or third-party solutions? It's bad enough that the JSON API is just a thin wrapper over an XML API, Authorize might as well just make it their sales pitch that they refuse to modernize anything...
