### ISSUE TITLE
Issue Sending Opaque Data Element

### ISSUE THREAD

**Issue by mikelunn** [AuthorizeNet/sdk-dotnet#165]
I'm trying to charge a credit card by replacing the creditCardType element with the opaqueData element from AcceptJs as follows:

 ```csharp
    var opaqueData = new { dataDescriptor = message.DataDescriptor, dataValue = message.DataValue };
            var paymentType = new paymentType { Item = opaqueData };
            var transactionRequest = new transactionRequestType
            {
                transactionType = transactionTypeEnum.authCaptureTransaction.ToString(),
                amount = message.Total,
                payment = paymentType
            };
```
I receive the following error when calling controller.execute(): "There was an error generating the XML document."

Does the SDK support the processing of the AcceptJS token?

**Comment by loga-mtsin** [comment]
We also encountered with the similar issue. Please let me know how this got closed ?

**Comment by rahulrnitc** [comment]
Hi @loga-mtsin,

Use `var opaqueData = new opaqueDataType { dataDescriptor = "COMMON.ACCEPT.INAPP.PAYMENT", dataValue = "dataValue" };`

You can find the sample code here: https://github.com/AuthorizeNet/sample-code-csharp/blob/master/MobileInappTransactions/CreateAnAcceptTransaction.cs

**Comment by mikelunn** [comment]
There wasn't much documentation in the C# examples about doing this. In my case I was creating an anonymous object to hold the token properties. I later discovered that the Authorize.net SDK had an opaqueDataType class. So this was the solution:

```
Incorrect way:
var opaqueData = new { dataDescriptor = message.DataDescriptor, dataValue = message.DataValue };
 var paymentType = new paymentType { Item = opaqueData };

Correct way:
 var opaqueToken = new opaqueDataType()
            {
                dataDescriptor = request.DataDescriptor,
                dataValue = request.DataValue
            };
 var paymentType = new paymentType { Item = opaqueToken };

```

**Comment by ameer988** [comment]
Hi @rahulrnitc ,
Greeting of the day!
We also same issue [How to find _opaqueData  dataValue_ ]
Your link not working: https://github.com/AuthorizeNet/sample-code-csharp/blob/master/MobileInappTransactions/CreateAnAcceptTransaction.cs

Please check and provide your sample code as soon as possible, @rahulrnitc. 

Thank you!

**Comment by ameer988** [comment]
C# code ?
