### ISSUE TITLE
getTransactionListResponse

### ISSUE THREAD

**Issue by dns12345** [AuthorizeNet/sdk-dotnet#172]
Thank you for a great SDK!

I discovered that customerProfileId and the customerPaymentProfileId are missing from the getTransactionList().  I can see them in the response XML on Authorize.Net API Reference "[Try It](http://developer.authorize.net/api/reference/index.html#transaction-reporting-get-transaction-list)" tab:

      <profile>
        <customerProfileId>1806660050</customerProfileId>
        <customerPaymentProfileId>1805324550</customerPaymentProfileId>
      </profile>

I would like to request "profile" property be added to transactionSummaryType:

Maybe this is too simple, but I thought something like this could be added?

    public partial class transactionSummaryType {        
        public string transId;
        public System.DateTime submitTimeUTC;
        public System.DateTime submitTimeLocal;
        public string transactionStatus;
        public string invoiceNumber;
        public string firstName;
        public string lastName;
        public string accountType;
        public string accountNumber;
        public decimal settleAmount;
        public string marketType;
        public string product;
        public string mobileDeviceId;
        public subscriptionPaymentType subscription;
        public bool hasReturnedItems;
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hasReturnedItemsSpecified;
        public fraudInformationType fraudInformation;
		
		/* possible new code???? */
		public profileType profile;
				
    }
	
	public partial class subscriptionPaymentType {
        public string customerProfileId;
        public string customerPaymentProfileId;
    }

Thanks so much for your consideration!

**Comment by dns12345** [comment]
It seems like "profile" is also missing from the getTransactionDetail() reponse too(?)

![image](https://cloud.githubusercontent.com/assets/27080167/24830945/c49b324c-1c5d-11e7-8626-3033a9298eca.png)

**Comment by chsriniv9** [comment]
profile information is added in both -
getTransactionList()
getTransactionDetail()
