### ISSUE TITLE
Static analysis security review identifies serialized delegate types as a security issue.

### ISSUE THREAD

**Issue by bbarry** [AuthorizeNet/sdk-dotnet#175]
We were running an [HP Fortify](https://www.hpfod.com) scan on our code and it decided to scan our dependency on AuthorizeNet.dll and reported a number of vulnerabilities related to the PropertyChanged events in the AnetApiSchema.xsd generated types such as: 

> #29180788 | ...izeNet.Api.Contracts.V1/KeyBlock.cs
> 
> ## Abstract
> 
> The class `KeyBlock` contains serializable `Delegate` field
> ## Explanation
> 
> `Delegate` type is used to hold reference to a method call that can be invoked later in the user code. .NET uses custom serialization while serializing `Delegate` types and utilizes the `System.DelegateSerializationHolder` class to store the method information that are attached or subscribed to a `Delegate`. So the serialized stream of `Delegate` object is not suitable for persistent storage or passing it to remote application, because an attacker could replace the method information with one which points to the malicious object graphs, which can cause an arbitrary code execution vulnerability when invoked on or after the deserialization.
> 
> 
>     [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
>     [System.SerializableAttribute()]
>     [System.Diagnostics.DebuggerStepThroughAttribute()]
>     [System.ComponentModel.DesignerCategoryAttribute("code")]
>     [System.Xml.Serialization.XmlTypeAttribute(Namespace="AnetApi/xml/v1/schema/AnetApiSchema.xsd")]
>     public partial class KeyBlock : object, System.ComponentModel.INotifyPropertyChanged {
>         
>         /// <remarks/>
>         public KeyValue Value;
>         
>         public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
>         
>         protected void RaisePropertyChanged(string propertyName) {
>             System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
>             if ((propertyChanged != null)) {
>                 propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
>             }
>         }
>     }
> 
> If the developer deserializes an untrusted stream of the above class mentioned in Example 1 and the attacker replaces the method information with one which points to the `Process.Start` method, it will lead to an arbitrary process to be created when the `RaisePropertyChanged` method is called.

As far as I can tell, none of these methods or events are ever called and they appear to be entirely unnecessary. Could they be regenerated with `EnableDataBinding` set to `false`?

**Comment by Purushottamlpa** [comment]
This is a **Public SDK** for developers to utilise in their applications/websites. 
The *INotifyPropertyChanged* allows developers to add their own handling as required, on any request/response fields.
Changing the base class which might have been inherited by other developers would **break their existing integration**. Hence, this change is not recommended.
