### ISSUE TITLE
dll strong name and version number

### ISSUE THREAD

**Issue by yys1694** [AuthorizeNet/sdk-dotnet#179]
Hello,
 
Is there any strong name version for authorize.net dll?
And authorize.net dll also doesn't have version number (only 0.0.0.0)
 
How should I get authorize.net dll with strong name and version number?
 
Thank you

**Comment by Purushottamlpa** [comment]
Hello, 

Currently Authorize .Net dll is not versioned. We will analyze this and address in later release.

**Comment by Externaluse** [comment]
Any update on this?

**Comment by ashtru** [comment]
Strong naming is not added, as Nuget packages released have are tied to the Github sourcecode.

Dll versioning has been added via AssmeblyInfo.cs in [PR#226](https://github.com/AuthorizeNet/sdk-dotnet/pull/226)

**Comment by gnongsie** [comment]
This has been released as part of v1.9.6. I'll be closing this issue now.
