### ISSUE TITLE
Enable logging and capture raw request & response? 

### ISSUE THREAD

**Issue by meetmandeep** [AuthorizeNet/sdk-dotnet#187]
Is there any documentation on how to enable logging to capture raw requests and responses?

**Comment by Purushottamlpa** [comment]
Hi,

There's no documentation on enable logging. However we do have Trace logs enabled in the application from where you can verify the raw requests and responses.

**Comment by skindogz** [comment]
I agree that you have Trace logs enabled.... how do I disable them? we have a console app that uses Trace for our own logs and don't want all of the authorize.net request/responses logged in our internal logs
