### ISSUE TITLE
ItemElementName Always Set To "sessionToken"

### ISSUE THREAD

**Issue by markwsanders** [AuthorizeNet/sdk-dotnet#188]
I believe I may have found a bug in `AuthorizeNet NuGet Package 1.9.3`.

I am writing a simple function to retrieve all active subscriptions from a sandbox account using `AuthorizeNet 1.9.3 NuGet Package`. Every time I run the code I receive `E00007 - User authentication failed due to invalid authentication values.` I have confirmed that I have the correct _**API Login ID**_ and _**Transaction Key**_ several times (including multiple _**Transaction Key**_ resets for good measure).

The issue is, no matter what I do the `MerchantAuthentication.ItemElementName` always end up being set to `ItemChoiceType.sessionToken`.

```C#
ApiOperationBase<ANetApiRequest, ANetApiResponse>.RunEnvironment = AuthorizeNetApi.Environment.SANDBOX;

ApiOperationBase<ANetApiRequest, ANetApiResponse>.MerchantAuthentication = new merchantAuthenticationType()
{
    name = ConfigurationManager.AppSettings["AuthorizeNetApiLoginId"],
    ItemElementName = ItemChoiceType.transactionKey,
    Item = ConfigurationManager.AppSettings["AuthorizeNetApiTransactionKey"]
};

var request = new ARBGetSubscriptionListRequest
{
    searchType = ARBGetSubscriptionListSearchTypeEnum.subscriptionActive
};

var controller = new ARBGetSubscriptionListController(request);

Trace.TraceInformation(request.merchantAuthentication.ItemElementName.ToString()); //outputs "sessionToken"

request.merchantAuthentication.ItemElementName = ItemChoiceType.transactionKey;

Trace.TraceInformation(request.merchantAuthentication.ItemElementName.ToString()); //outputs "sessionToken"

var response = controller.ExecuteWithApiResponse();

Trace.TraceInformation(response.messages.resultCode.ToString()); //outputs "Error"
Trace.TraceInformation($"{response.messages.message[0].code} - {response.messages.message[0].text}"); //outputs "E00007 - User authentication failed due to invalid authentication values."
```

If I revert to AuthorizeNet NuGet Package 1.9.2 and run the exact same code block (no changes) then the functions runs correctly and returns the list without error, as expected.

**Comment by Purushottamlpa** [comment]
Hi, 

We used above code and this works fine with AuthorizeNet NuGet Package 1.9.3. Could you please confirm if you are still facing  this issue?

**Comment by Purushottamlpa** [comment]
Thank you for raising this issue. We have had some releases since the issue was raised, and we hope that these updates have resolved your asks. We are therefore closing this issue. Please raise a new issue, if you’re still facing problems, and we’ll look into it quickly.
