### ISSUE TITLE
Which API Calls should we be using for CIM?

### ISSUE THREAD

**Issue by chassq** [AuthorizeNet/sdk-dotnet#189]
Just a clarification. I think I am seeing 2 different avenues to call CIM. There is the way described in the API docs (e.g. http://developer.authorize.net/api/reference/index.html#customer-profiles) and another way as specified in the CustomerGateway tests (i.e. https://github.com/AuthorizeNet/sdk-dotnet/blob/master/AuthorizeNETtest/CustomerGatewayTest.cs). Any guidance on which is the appropriate one to use? The CustomerGateway calls seem to be the more recent? Any help appreciated.

**Comment by NexWeb** [comment]
As long as the JSON or XML getting posted to the API comes out the same as specified at : http://developer.authorize.net/api/reference/index.html#customer-profiles, as far as the API is concerned, it doesn't matter which road you took to get there.

**Comment by chassq** [comment]
Ok great. Just wanted to make sure Auth NEt was not deprecating any specific path anytime soon. Much appreciated!
