### ISSUE TITLE
ReportingGateway GetSettledBatchList Use DateTime.Now instead of DateTime.Today

### ISSUE THREAD

**Issue by wrathburn** [AuthorizeNet/sdk-dotnet#190]
The default **GetSettledBatchList()** method should use **DateTime.Now** instead of DateTime.Today to ensure the last 30 batches is actually the last 30 settled batches.  Currently, if batches are set to settled after midnight (same day as Today but really early in the morning like 0100 hours), when calling the GetSettledBatchList() default method will not return the most recent settled batch.  It will exclude the batch settled at 0100 hours of the same day.  The same logic applies to the **GetTransactionList()** method.

	public List<Batch> GetSettledBatchList(bool includeStats) 
	{
		var from = DateTime.Now.AddDays(-30);
		var to = DateTime.Now;
		return GetSettledBatchList(from, to, includeStats);
	}

	public List<Batch> GetSettledBatchList() 
	{
		var from = DateTime.Now.AddDays(-30);
		var to = DateTime.Now;
		return GetSettledBatchList(from, to, false);
	}

	public List<Transaction> GetTransactionList() 
	{
		return GetTransactionList(DateTime.Now.AddDays(-30), DateTime.Now);
	}

**Comment by Purushottamlpa** [comment]
This API is designed to give last 30 days report excluding today's. We can not make modifications here as it will impact other users. 
However, you can use public method GetSettledBatchList(from, to, includeStats) by passing expected from and to date.
