### ISSUE TITLE
NetStandard 2.0

### ISSUE THREAD

**Issue by chassq** [AuthorizeNet/sdk-dotnet#196]
When are you going to support NetStandard Lib 2.0?

**Comment by vishalmgiri** [comment]
Any update on .net Core1 or Core 2 support.
Or walkthrough link for implementing same.

**Comment by jasongaylord** [comment]
@vishalmgiri @chassq Not sure if it helps, but we started our own version based on our needs. It's available at https://github.com/biBERK/AuthorizeNet-dotnetcore. We haven't pushed our package to the public NuGet servers just yet as it's still pre-release and not everything has been tested.

**Comment by vishalmgiri** [comment]
Thanks for update @jasongaylord , we will review it.

**Comment by jasongaylord** [comment]
@vishalmgiri No worries. We've been able to test this function end to end. While I changed the version to 1.0.0, I haven't pushed it to NuGet just yet.

**Comment by Purushottamlpa** [comment]
Thanks for the query. We are working on this and will provide .NET core and Standard support in   next major release.

**Comment by mrahl** [comment]
Do you have an estimate for when the netstandard compatible version may be available?

**Comment by jasongaylord** [comment]
It's fairly straight forward @mrahl. We didn't implement all of the functionality that you may need or want, but of course pull requests are welcome.

**Comment by chsriniv9** [comment]
We are working on releasing .Net Core sdk and should be available in July.

**Comment by jrlang1** [comment]
.net core or .net standard?

**Comment by ashtru** [comment]
@jrlang1 
It is .Net core.

**Comment by mathewrg** [comment]
@chsriniv9, @ashtru any updates on this? Thanks..

**Comment by chsriniv9** [comment]
@dgoranov, @mathewrg  
.Net Core sdk is going through last leg of QA and release rituals, should get completed in couple of weeks for it to be published. 

Thanks for your patience and support !!

**Comment by mathewrg** [comment]
Excellent!! Appreciate all your good work..

**Comment by leniency** [comment]
> @chsriniv9 : We are working on releasing .Net Core sdk and should be available in July.
> 
> Any update on the .Net Core SDK? It is already the end of August.

November now, still no word?

**Comment by mitchcapper** [comment]
@leniency @yasref any reason you don't use PR #200 ? It works just fine in .net standard.

**Comment by leniency** [comment]
> @leniency @yasref any reason you don't use PR #200 ? It works just fine in .net standard.

I'm going to have to, it's just a minor bit of overhead get it all setup.

**Comment by chsriniv9** [comment]
Team,

ANET .Net Core SDK Beta Release is available in the [repo](https://github.com/AuthorizeNet/dotnet-core-sdk-beta). The release took longer than anticipated, apologies for the delay. Please use this beta release and provide if there are any feedback.

Thanks again for your patience and support !!

**Comment by gnongsie** [comment]
Hi @nhustak ,

The .Net Core SDK was released as a beta release. It will not be available in NuGet for now. It is only available as part of the repo.

I will discuss with the team if it is possible to have a pre-release version available in NuGet.


Regards,
Gabriel

**Comment by gnongsie** [comment]
Hi @nhustak ,

As mentioned in the previous comment, the .Net Core SDK will not be available in NuGet for now.

To facilitate testing by the developer community, we have pre-compiled the SDK and placed it in [ReleaseArtifact](https://github.com/AuthorizeNet/dotnet-core-sdk-beta/tree/master/ReleaseArtifact) folder.

**Comment by nhustak** [comment]
@gnongsie Cool thanks guys!

**Comment by nhustak** [comment]
Guys,  where do we stand on this?  It's been months and months.  I see a new 2.0.1 release for Framework but I see very little movement here and, frankly, I'm getting seriously concerned.    I don't consider this issue remotely closed.    It's way beyond time for this to be released.   No one in their right mind is starting a new project in Framework.   I'm having to jump through hoops to continue to use you guys  - I have impending releases in .NET Core and I'm not pleased with having to create my own wrappers.  Don't make me go looking for another merchant.

**Comment by fizch** [comment]
I saw something about Core version. I was upset that they did not come with a Standard version. I mentioned my displeasure in another issue, but there has been response to that.

**Comment by nhustak** [comment]
Yes it needs to be standard, not core.
