### ISSUE TITLE
getAUJobDetailsController not available in release 1.9.3

### ISSUE THREAD

**Issue by Jabberrwocky** [AuthorizeNet/sdk-dotnet#197]
Hi,

I am trying to use the `AuthorizeNet.Api.Controllers.getAUJobDetailsController` class, but, while the file exists, it is not included in the project, so I cannot reference it in my project.

I have downloaded your source and have added it back into the project, but was wondering if there was a reason why it was left out.

Thanks.

**Comment by Purushottamlpa** [comment]
Hi, 

Thanks for writing to Authorize .Net. 

For releases 1.9.3 and prior,  getAUJobDetailsController was officially not part of SDK. Hence, there was no support or monitoring for this. With 1.9.4 it is released and you can fork the latest branch and can access them.

Please revert on your progress and confirm this resolved your issue.

**Comment by Jabberrwocky** [comment]
Thank you for responding. I got 1.9.4 and everything looks good so far.
