### ISSUE TITLE
Getting null while fetching the already created payment profile in authorize.net

### ISSUE THREAD

**Issue by Divya-motivitylabs** [AuthorizeNet/sdk-dotnet#198]
I have created a profile as well as payment profile for a user. But while updating the payment profile by using the same key, it is throwing error saying "payment profile does not exist".

"Pamela Hollick" with email-id : Pamela.h.hollick@gmail.com is one such user.

**Comment by gnongsie** [comment]
Hi, can you provide us the steps you performed in order for us to reproduce this error?
Just for clarity, I'm assuming you received successful responses for both the create profile and create payment profile.

**Comment by Divya-motivitylabs** [comment]
Yes, I had received successful responses for both. Also I have saved the authorization key in our database. But while updating the payment profile for the next payment cycle with the same payment profile, it is throwing error saying "payment profile does not exist".

I am not getting, how the payment profile got deleted in authorize.net.

**Comment by gnongsie** [comment]
Hi, can you provide the requests that you sent for creating the profiles? I am not entirely sure what the "authorization key" is. 
Also, can you tell us whether you are seeing this behavior for more than one profile or just a single profile?

**Comment by Divya-motivitylabs** [comment]
"authorization key" refers to the payment profile id.

Yes, i have seen this for more than 10 users, either the 'payment profile' is missing in authorize.net or the 'payment profile id' does not match.

Moreover, I am not able to use 'https://apitest.authorize.net/soap/v1/Service.asmx?wsdl' for testing on local, can you please help me out. I am totally stuck now.

**Comment by adavidw** [comment]
Is this in sandbox or production? If in production, does the account have the account updater service turned on? When the account updater service gets an ACL (account closed) or CCH (contact cardholder) response for a particular payment profile that payment profile is deleted.

You can know for sure whether or not this has happened by checking the account updater reports in the Merchant Interface, or checking the account updater reports through the API.

**Comment by Divya-motivitylabs** [comment]
It is in production. Let me check the account updater service.

**Comment by Divya-motivitylabs** [comment]
I am not able to use 'https://apitest.authorize.net/soap/v1/Service.asmx?wsdl' for testing on local, can you please help me out. I am totally stuck now.

**Comment by gnongsie** [comment]
If you are testing this in production, then you are using the wrong URL for the WSDL. But I'm guessing these are two different issues.

Can you provide us with the requests you are using for creating and for updating? You can omit the sensitive data (just give some random stuff there). If you prefer, you can mail them to me at gnongsie@visa.com.

**Comment by Divya-motivitylabs** [comment]
Yes, these are 2 different issues. 

I am calling the createProfile service to create the profile and payment profile in authorize.net.

In return, it gives me profile id and payment profile id.
But after 1 month, when the same user tries to update the card details, she is getting error 'payment profile does not exist'.

Updating the card details is working fine for rest of the users. 

I am not having the requests right now as these all are production users. secondly, I am not able to replicate the same on local as the test service is not working.

**Comment by Divya-motivitylabs** [comment]
Hey, I got it. 
The "account updater service" is ON. that is why the payment profiles were getting deleted. Is there any way we can get to know what all payment profiles got deleted??

**Comment by gnongsie** [comment]
Hi,

You can check in your Merchant Interface account and look in the Account Updater section for this information.

You can alternatively use these APIs for checking that information:
1. [Get Account Updater Summary](http://developer.authorize.net/api/reference/index.html#transaction-reporting-get-account-updater-job-summary)
2. [Get Account Updater Job Details](http://developer.authorize.net/api/reference/index.html#transaction-reporting-get-account-updater-job-details)

**Comment by Divya-motivitylabs** [comment]
Is there any support for SOAP projects also???
