### ISSUE TITLE
Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by natelaff** [AuthorizeNet/sdk-dotnet#199]
All of the sudden (not sure when exactly), my development PC can no longer execute against the authorize.net API.

A call to ExecuteWithApiResponse() is met with The request was aborted: Could not create SSL/TLS secure channel.

Luckily it still seems to be working in production. What changed?

**Comment by adavidw** [comment]
What changed is that TLS 1.0 and 1.1 have been disabled in sandbox (https://community.developer.authorize.net/t5/The-Authorize-Net-Developer-Blog/TLS-1-1-and-1-0-Disabled-in-Sandbox-on-April-30-2017-Updated-2X/ba-p/57726). The same will be true of production in February 2018.

The .NET SDK will support TLS 1.2 connections, but you may have to upgrade components on your end, and might have to explicitly set up a TLS 1.2 connection in your code. Check through the issues here, or browse through our forums (https://community.developer.authorize.net), and you'll likely find someone else who's had your combination of OS version and .NET version and already posted a workaround. If not, come back here and we'll help you figure it out.

**Comment by natelaff** [comment]
Thanks. I had actually just found that other issue about the same thing (different error message though).

I'm able to upgrade to .NET 4.7 and just did that and everything seems to be working now by default

**Comment by edencorbin** [comment]
I'm working on a site in production with .net 4.5, how would I confirm if I am or am not using a TLS 1.2 connection?

  <package id="AuthorizeNet" version="1.8.3" targetFramework="net45" />
