### ISSUE TITLE
protocol_version error while using testapi

### ISSUE THREAD

**Issue by Divya-motivitylabs** [AuthorizeNet/sdk-dotnet#201]
While using https://apitest.authorize.net/soap/v1/Service.asmx I am getting protocol_version error.

![2017-09-15 12_44_29-tridot](https://user-images.githubusercontent.com/30148948/30540622-7c95e894-9c95-11e7-9ea4-d66ef4ecda11.png)

Attached is the error message I am getting.

**Comment by kikmak42** [comment]
This the correct URL for the WSDL : https://apitest.authorize.net/soap/v1/Service.asmx?wsdl
Also, I won't recommend you to use SOAP instead use the HTTP xml APIs via this SDK.

**Comment by Divya-motivitylabs** [comment]
I am using the same URL. It is throwing error in UAT enviornment

**Comment by gnongsie** [comment]
Hi,
Is it possible to provide the proper error message coming from the site? This does not seem like the full/proper message.

**Comment by gnongsie** [comment]
Incidentally, it could also be due to this issue #199 . Can you check if your components support TLS 1.2 connections?

**Comment by Divya-motivitylabs** [comment]
How can i check whether my components support TLS 1.2 connections or not? 
Its a linux machine

**Comment by gnongsie** [comment]
Can you take a look at this: https://stackoverflow.com/a/27545567/2620467 ?

**Comment by Divya-motivitylabs** [comment]
I had already gone through this. After using the command
**openssl ciphers -v | awk '{print $2}' | sort | uniq**
 It is giving me 
**SSLv3
TLSv1.2**

**Comment by Divya-motivitylabs** [comment]
That means, my component support TLS 1.2 connections. But I am not able to connect to the test service.

Is there any dependency on Java version also?
