### ISSUE TITLE
The request was aborted: Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by memphisguy123** [AuthorizeNet/sdk-dotnet#203]
I am using the sandbox to test Authorize.net in Dynamics AX. I am getting this error

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.

I have upgraded to .net 4.6 but still getting the error.

**Comment by NexWeb** [comment]
Using the sample code?  I made PR #65.

**Comment by NexWeb** [comment]
```
using System.Security.Authentication;
using System.Net

            const SslProtocols _Tls12 = (SslProtocols)0x00000C00;
            const SecurityProtocolType Tls12 = (SecurityProtocolType)_Tls12;
            ServicePointManager.SecurityProtocol = Tls12;
```

**Comment by njsimha30** [comment]
NexWeb, I had the same issue and your solution worked. Thanks.

**Comment by NexWeb** [comment]
@njsimha30, very good. Glad to hear it.

**Comment by digioz** [comment]
This is great @NexWeb . Thanks for the help!

**Comment by bhautik1907** [comment]
You are a LEGEND! Thanks

**Comment by MikeOtown** [comment]
VB version?
