### ISSUE TITLE
AuthorizeNet.dll doesn't contain version info

### ISSUE THREAD

**Issue by vietanh-epi** [AuthorizeNet/sdk-dotnet#209]
Hi,
I installed AuthorizeNet 1.9.4 using nuget.
I noticed that the dll file doesn't contain version info. Is it correct?
![authorizenetproperties](https://user-images.githubusercontent.com/33282505/33253300-5d29d56c-d375-11e7-8f2e-6e5103cfd8a9.PNG)

**Comment by rahulrnitc** [comment]
The version info was not present in any of the previous versions. So this behaviour is as expected.

**Comment by cforbesywam** [comment]
People using NuGet are expecting to see a version number on the assemble - that is consistent with the package version - this is standard practice these days.  Please add the version number to the assembly info.

![missingversion](https://user-images.githubusercontent.com/10047139/52305865-7c8ab400-2953-11e9-9f15-20a067d6b329.png)

![assemblyversion](https://user-images.githubusercontent.com/10047139/52305864-7c8ab400-2953-11e9-8cd9-c4a1c756064d.png)
