### ISSUE TITLE
HttpXmlUtility.DecideResponse()  case "ARBGetSubscriptionListResponse is missing

### ISSUE THREAD

**Issue by schernokov** [AuthorizeNet/sdk-dotnet#210]
In HttpXmlUtility in  "DecideResponse(XmlDocument xmldoc)" method the case is missing that deals with ARBGetSubscriptionListResponse. I allows to retrieve the list of ARBs. Can anyone add the following (I submitted the file change, but I am not certain if I did it correctly):

                    case "ARBGetSubscriptionListResponse":
                        serializer = new XmlSerializer(typeof(ARBGetSubscriptionListResponse));
                        apiResponse = (ARBGetSubscriptionListResponse)serializer.Deserialize(reader);
                        break;

**Comment by schernokov** [comment]
also, need to add the following to be able to retrieve the details of an ARB

 case "ARBGetSubscriptionResponse":
                        serializer = new XmlSerializer(typeof(ARBGetSubscriptionResponse));
                        apiResponse = (ARBGetSubscriptionResponse)serializer.Deserialize(reader);
                        break;

**Comment by maninder-puhi** [comment]
Hi @schernokov,

Can you check the sample codes for [ARBGetSubscriptionListResponse](https://github.com/AuthorizeNet/sample-code-csharp/blob/master/RecurringBilling/GetListOfSubscriptions.cs) and [ARBGetSubscriptionResponse](https://github.com/AuthorizeNet/sample-code-csharp/blob/ad0ebda64f706058ae1efa87932c8a9f979bd87e/RecurringBilling/GetSubscription.cs)?

These should serve your requirements. Feel fee to reach out to us in case of any queries.

**Comment by chsriniv9** [comment]
Closing for now based on the suggestion provided by @maninder-puhi.

Please feel free to open if needed.
