### ISSUE TITLE
Issue with Apple Pay transactions

### ISSUE THREAD

**Issue by dannny** [AuthorizeNet/sdk-dotnet#213]
Hi,

I've been trying to perform a createTransactionRequest with type "authOnlyTransaction" for Apple Pay.
However I always get back an error of 

"There was an error processing the payment data. Opaque data can only be used with ECOM market type."

Upon traversing the code here, I believe the transactionRequest.retail.marketType is always getting overridden to "2" even when I set it to "0" for ecommerce type.

[RequestFactoryWithSpecified.cs]
```
public static void transRetailInfoType(transRetailInfoType argument)
{
    if (null != argument)
    {
        argument.marketType = "2";
    }
}
```

**Comment by maninder-puhi** [comment]
Hi @dannny,

We are looking into this issue. Can you please send over the XML request which you are trying?
Please email the request to manindersinghpuhi@gmail.com.

**Comment by vijayabraj** [comment]
Hi @dannny,

The marketType need not be explicitly set to "0" for ApplePay transaction. They are processed as ECommerce transactions only.

Can you share the request you are sending to the SDK without sensitive information with me on bselvara@visa.com? It'd be helpful for us to understand how you are trying to use this API call?

-Barath

**Comment by dannny** [comment]
Hi @vijayabraj , yes I do explicitly set that to 0, the request looks like this:

```
var transaction = new transactionRequestType
{
	transactionType = transactionTypeEnum.authOnlyTransaction.ToString(),
	amount = amount,
	payment = new paymentType
	{
		Item = new opaqueDataType
		{
			dataDescriptor = "COMMON.APPLE.INAPP.PAYMENT",  // this is the value for Apple Pay
			dataValue = token
		}
	},
	order = new orderType
	{
		invoiceNumber = transactionId,
		description = transactionId
	},
	retail = new transRetailInfoType
	{
		marketType = "0", // 0=ecommerce
		deviceType = "9", // 9=Dial Terminal
	}
};

var request = new createTransactionRequest
{
	transactionRequest = transaction,
	refId = refId
};

var response = new createTransactionController(request).ExecuteWithApiResponse();
```

**Comment by vijayabraj** [comment]
Hi @dannny, This issue is fixed now. Can you please check it from your side?

**Comment by vijayabraj** [comment]
Hi @dannny , the new Nuget package for Authorize.Net 1.9.5 is available now which contains the fix. You can check it at your end now.

**Comment by chsriniv9** [comment]
Issue addressed in the latest release - https://github.com/AuthorizeNet/sdk-dotnet/releases/tag/1.9.5
Hence closing this issue.
