### ISSUE TITLE
https://apitest.authorize.net/soap/v1/Service.asmx - Sandbox with TLS1.0 disabled?

### ISSUE THREAD

**Issue by kevops** [AuthorizeNet/sdk-dotnet#214]
Our test environment is configured to hit this endpoint - https://apitest.authorize.net/soap/v1/Service.asmx

I'm wondering if we are hitting the sandbox already that has TLS 1.0 and TLS 1.1 disabled.

**Comment by adavidw** [comment]
TLS 1.0 and 1.1 have been disabled on all possible sandbox endpoints since May 1, 2017

**Comment by brianmc** [comment]
Mr @adavidw  is absolutely right, our sandbox only supports TLS 1.2
