### ISSUE TITLE
Order Only - Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by markewing** [AuthorizeNet/sdk-dotnet#215]
I am working with the CoffeeShopWebApp example and on the Payment Information screen "Order with DPM!" and "Order with SIM!" work fine, but when I click the "Order" button, I get the dreaded error:
Could not create SSL/TLS secure channel.

Any help would be greatly appreciated.

**Comment by maninder-puhi** [comment]
Hi @markewing,

Thanks for pointing out the issue. I have created a pull request #217 to address this issue.
Once this is merged Order button funtionality will be in place.

**Comment by gnongsie** [comment]
This has been released as part of v1.9.5. I'll be closing this issue now.
