### ISSUE TITLE
Certificate change causing error code 13 with no way to update the Gateway URL

### ISSUE THREAD

**Issue by digioz** [AuthorizeNet/sdk-dotnet#218]
Since 2 months or so ago we have been getting a code 13 Error when trying to post transactions using this Nuget Package. When talking to Authorize.net support, we were told this is due to a Certificate change that Authorize.net made a few months ago, and recommended that we use alternate URLs to post the transaction. 

It doesn't look like there is an easy way to change the URL using this DLL. Could you please suggest a work around for this or add a feature to allow for overriding the Gateway URLs in Live Mode?

**Comment by digioz** [comment]
We verified with Authorize.net support that both the login ID and password are correct. The support folks were the ones that told us this.

**Comment by maninder-puhi** [comment]
Can you provide the version of Nuget package you are using and the code you are using to integrate?

**Comment by maninder-puhi** [comment]
I see you are using an example similar to [AuthorizationRequest.cs](https://github.com/AuthorizeNet/sdk-dotnet/blob/3c310c5ad41145685431fe49b94d77ddb4f4835a/Authorize.NET/AIM/Requests/AuthorizationRequest.cs) which does not allow you to customize the request endpoint.

**Can you please try rewriting your code similar to the latest sample codes?**
Here is a sample code that covers all of your requirements including merchant authentication, credit card info, and lineitems and also the request endpoint at line [#18](https://github.com/AuthorizeNet/sample-code-csharp/blob/ad0ebda64f706058ae1efa87932c8a9f979bd87e/PaymentTransactions/ChargeCreditCard.cs#L18) in this file:
**https://github.com/AuthorizeNet/sample-code-csharp/blob/ad0ebda64f706058ae1efa87932c8a9f979bd87e/PaymentTransactions/ChargeCreditCard.cs** 
`  ApiOperationBase<ANetApiRequest, ANetApiResponse>.RunEnvironment = AuthorizeNet.Environment.SANDBOX;
`

**Comment by digioz** [comment]
Thanks! I updated our code to match the sample code you provided and it did indeed fix the issue. 

This is very much appreciated!
