### ISSUE TITLE
createCustomerPaymentProfileController response throws exception when cardNumber is blank

### ISSUE THREAD

**Issue by pelletierjason** [AuthorizeNet/sdk-dotnet#225]
When using createCustomerPaymentProfileController, when I pass an invalid cardNumber in the paymentType, for example cardNumber = "1234", the endpoint returns this response:

`<?xml version="1.0" encoding="utf-8"?>
<createCustomerPaymentProfileResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd">
	<messages>
		<resultCode>Error</resultCode>
		<message>
			<code>E00015</code>
			<text>The field length is invalid for Card Number.</text>
		</message>
	</messages>
</createCustomerPaymentProfileResponse>`

This is parsed properly by the XmlParser. However, when make the same request with cardNumber = "", the response returned is:

`<?xml version="1.0" encoding="utf-8"?>
<createCustomerPaymentProfileResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="AnetApi/xml/v1/schema/AnetApiSchema.xsd">
	<messages>
		<resultCode>Error</resultCode>
		<message>
			<code>E00015</code>
			<text>The field length is invalid for Card Number.</text>
		</message>
	</messages>
</createCustomerPaymentProfileResponse>`

This causes the following exception to occur:

`<ErrorResponse xmlns='AnetApi/xml/v1/schema/AnetApiSchema.xsd'> was not expected.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReadercreateCustomerPaymentProfileResponse.Read7_Item()`

I'm not sure why the API doesn't respond with the invalid length error message for both of these requests, but it is problematic to have the exception thrown.

Thanks!

**Comment by Purushottamlpa** [comment]
There are two validation applicable on card number. 
1. Schema validation using schema 
2. Server side validation

Empty value or length less than < 4 of the field is validated against schema which gives "**The 'AnetApi/xml/v1/schema/AnetApiSchema.xsd:cardNumber' element is invalid - The value XX is invalid according to its datatype 'String' - The actual length is less than the MinLength value.**" 

For any other use case, request will be send to server and validated there response is 
 "The field length is invalid for Card Number."

**Comment by chsriniv9** [comment]
As per inputs provided by @Purushottamlpa closing this issue. If there are any further queries feel free to re-open
