### ISSUE TITLE
How do you generate a token/cryptogram via the .NET SDK?

### ISSUE THREAD

**Issue by ZacP** [AuthorizeNet/sdk-dotnet#230]
I understand how to process a payment via the transaction request and setting the cryptogram on the creditCardType.  However, I don't understand how to generate the token via the API.  I'd expect that we'd pass in the CC information via a "get token" transaction type and then use that token instead of the CC information moving forward.  I can't find a method that allows this.  

Any suggestions on how to do this would be greatly appreciated.

**Comment by kikmak42** [comment]
Hi @ZacP to generate a token/cryptogram which can be used to charge a credit card you will need the token to be issued by a certified token provider like Apple/Android/Samsung, and then use the charge tokenized card API.

So, if you want to pass the CC details only once and charge it later you can you the Card-on-file or better known as [Customer Profile](https://developer.authorize.net/api/reference/index.html#customer-profiles) feature of Authorize.Net.

Create a [Customer Payment Profile](https://developer.authorize.net/api/reference/index.html#customer-profiles-create-customer-profile) for the customer and in response you get back an ID. You can later use the ID in the [Charge Customer Profile API](https://developer.authorize.net/api/reference/index.html#payment-transactions-charge-a-customer-profile) to charge the CC.

**Comment by gnongsie** [comment]
Based on @kikmak42 's reply, I'm closing this issue. Kindly reopen if there are any further questions.
