### ISSUE TITLE
Environment does not contain a definition for 'Environment'

### ISSUE THREAD

**Issue by RambosRide** [AuthorizeNet/sdk-dotnet#233]
![aneterr](https://user-images.githubusercontent.com/8228156/45463159-e1e9ba00-b6bf-11e8-8bc0-2084b9381e50.jpg)
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0117	'AuthorizeNet' does not contain a definition for 'Environment'

Sigh..out of the box install from Nuget Fails

Downloaded bits from github
fixed xml comment errors in  .\sdk-dotnet-master\Authorize.NET\Environment.cs
and recompiled, and referenced new dll in my project -  STILL the same ERROR.

I CANNOT be the only person having this issue with the latest release :)

Any help would be greatly appreciated.

Thanks!

**Comment by RambosRide** [comment]
Found the problem, rookie mistake on my end....nothing to see here...

**Comment by jibboo** [comment]
glad you figured it out ... what is the answer?

**Comment by naveenrevalino** [comment]
I am getting the same error when i tried to implement the Create Customer Profile.
What is the solution, can you share it please.

**Comment by jibboo** [comment]
I've got this all up and running.  I created a separate class to handle all the Authorize.Net calls ... I created this code based on the API reference info (https://developer.authorize.net/api/reference/index.html#customer-profiles-create-customer-profile)

`using AuthorizeNet.Api.Controllers;
using AuthorizeNet.Api.Contracts.V1;
using AuthorizeNet.Api.Controllers.Bases;

public class AuthNet
    {
        const string PaymentMode = "LIVE";           // "LIVE" or "sandbox"

        /// <summary>
        /// switch between Sandbox and LIVE
        /// </summary>
        protected static void GetMerchantLogin()
        {
            if (string.Equals(PaymentMode, "LIVE"))
            {   // set whether to use the sandbox environment, or production enviornment
                ApiOperationBase<ANetApiRequest, ANetApiResponse>.RunEnvironment = AuthorizeNet.Environment.PRODUCTION;
                // define the merchant information (authentication / transaction id)
                ApiOperationBase<ANetApiRequest, ANetApiResponse>.MerchantAuthentication = new merchantAuthenticationType()
                {
                    name = "{yourAPILoginID}",                  // API Login ID under (account.authorize.net / Settings / API Credentials & Keys) 
                    ItemElementName = ItemChoiceType.transactionKey,
                    Item = "{youTransactionKey}",               // Transaction Key under (account.authorize.net / Settings / API Credentials & Keys) 
                };
            }
            else
            {   // set whether to use the sandbox or production 
                ApiOperationBase<ANetApiRequest, ANetApiResponse>.RunEnvironment = AuthorizeNet.Environment.SANDBOX;
                // define the merchant information (authentication / transaction id)
                ApiOperationBase<ANetApiRequest, ANetApiResponse>.MerchantAuthentication = new merchantAuthenticationType()
                {
                    name = "{sandboxAPILoginID}",               // API Login ID under (sandbox.authorize.net / Settings / API Credentials & Keys)
                    ItemElementName = ItemChoiceType.transactionKey,
                    Item = "{sandboxTransactionKey}",           // Transaction Key under (sandbox.authorize.net / Settings / API Credentials & Keys)
                };
            }
        }

        /// <summary>
        /// Create Customer Profile
        /// </summary>
        public static createCustomerProfileResponse CreateProfile(customerProfileType customerProfile)
        {
            GetMerchantLogin();

            createCustomerProfileRequest request = new createCustomerProfileRequest
            {
                profile = customerProfile,
                validationMode = validationModeEnum.testMode            // Use testMode to perform a Luhn mod-10 check on the card number, without further validation. 
                                                                        // Use liveMode to submit a zero-dollar or one-cent transaction
            };

            // instantiate the controller that will call the service
            createCustomerProfileController controller = new createCustomerProfileController(request);
            controller.Execute();

            // get the response from the service (errors contained if any)
            createCustomerProfileResponse response = controller.GetApiResponse();

            return response;
        }   // end of CreateProfile
}   // end class
`

I call this library from my join section with code similar to this:  I'm populating the customer profile data from my user object. 

`
string customerProfileId = string.empty;             // variable to hold created Customer Profile ID
string paymentProfileId  = string.empty;             // variable to hold created Payment Profile ID

customerAddressType billto = new customerAddressType
{
    firstName = user.FirstName,
    lastName = user.LastName,
    address = user.Street,
    city = user.City,
    state = user.State,
    zip = user.Zip,
    country = user.Country,
    phoneNumber = user.Phone,
    email = user.Email
};

paymentType paymentType = new paymentType
{
    Item = new creditCardType
    {   // credit card info
        cardNumber = user.CreditCardNumber,                // Numeric string, 13-16 digits.
        expirationDate = user.Expiration,               // Use XML gYearMonth (YYYY-MM) formatting.
        cardCode = user.CVVCode                  // Numeric string, 3-4 digits.
    }
};

customerPaymentProfileType ccPaymentProfile = new customerPaymentProfileType
{
    defaultPaymentProfile = true,
    customerType = customerTypeEnum.individual,
    billTo = billto,                    // billto defined above in Auth/Capture transaction
    payment = paymentType               // payemntType / CC defined above in Auth/Capture transaction
};
List<customerPaymentProfileType> paymentProfileList = new List<customerPaymentProfileType>();
paymentProfileList.Add(ccPaymentProfile);
List<customerAddressType> addressInfoList = new List<customerAddressType>();
addressInfoList.Add(billto);

customerProfileType customerProfile = new customerProfileType
{
    merchantCustomerId = user.UserID,
    email = user.Email,
    profileType = customerProfileTypeEnum.regular,
    paymentProfiles = paymentProfileList.ToArray(),
    shipToList = addressInfoList.ToArray()
};
// this is the call to the AuthNet class library from above
createCustomerProfileResponse profileresponse = AuthNet.CreateProfile(customerProfile);
if (profileresponse != null)
{
    if (profileresponse.messages.resultCode == messageTypeEnum.Ok)
    {
        customerProfileId = profileresponse.customerProfileId;
        if (profileresponse.customerPaymentProfileIdList.Length > 0)
        {
            paymentProfileId = profileresponse.customerPaymentProfileIdList[0];
        }
    }
    else
    {   // an error occurred creating profile
        string errmsg = "Error: " + profileresponse.messages.message[0].code + "  " + profileresponse.messages.message[0].text;
        errmsg += "<br/>Unable to create your customer profile.<br/>Please <a href='contact'>contact us</a> if you need help.";
    }
}
else
{   // error creating profile (likely issue with params)
    string errmsg = "Error: >Unable to create the user payment profile.";
}
`

**Comment by jibboo** [comment]
If using Visual Studio with Nuget, here's the package I installed:


![image](https://user-images.githubusercontent.com/6004104/78728714-0e9a9d80-7906-11ea-96b7-3b1c59dbb297.png)

**Comment by bruestle** [comment]
I got the same error, 'AuthorizeNet' does not contain a definition for 'Environment'.  

ApiOperationBase<ANetApiRequest, ANetApiResponse>.RunEnvironment = AuthorizeNet.Environment.SANDBOX;

Tried reloading the nuget 2.0.1.

**Comment by bruestle** [comment]
Found it.  I had named my class AuthorizeNet so the reference to AuthorizeNet.Environment.SANDBOX was looking for Environment in my own class.  Dummy me.
