### ISSUE TITLE
Latency Issue

### ISSUE THREAD

**Issue by ammar91** [AuthorizeNet/sdk-dotnet#239]
Hi,

We have the following api end point integrated

https://developer.authorize.net/api/reference/index.html#payment-transactions-charge-a-credit-card

We recently start getting complaints from our customer where the payment went through successfully and receipt came into merchant email but they stuck on payment form. And the reason we found out after the request initiate to authroize.net, customer get's charged immediately but sometime it takes very long to get acknowledgement back and as result customer's keep waiting on payment page and get frustrated and feel like it hung and they close there session.

Even though we set the following timeout parameters in web.config to 20 sec but looks it does not respect those. And it keeps waiting for acknowledgement.

<add key="http.connectionTimeout" value="20000"/>
<add key="http.readWriteTimeout" value="20000"/>

We haven't made any code changes on our side  for a long but that start happening recently. Seems like there is latency issue that recently introduce in the system and does not relate to timeout issue.

**Comment by chsriniv9** [comment]
Hi @ammar91,

Please share if you are still observing this issue as this could be an intermittent glitch. Revert if you need any support.

HTH, Thanks

**Comment by chsriniv9** [comment]
Hi @ammar91 ,

Closing this issue assuming that the reported issue was intermittent, please feel free to re-open if you need any further assistance.

Thanks
