### ISSUE TITLE
Anticipated changes for MD5 Hash End of Life & Signature Key Replacement

### ISSUE THREAD

**Issue by sebastians86** [AuthorizeNet/sdk-dotnet#247]
This is more of a question rather than an issue.

Will the changes described in [this article](https://support.authorize.net/s/article/MD5-Hash-End-of-Life-Signature-Key-Replacement?utm_campaign=19Q2+MD5+Hash+EOL+Developer&utm_medium=email&utm_source=Eloqua) affect at all the functionality of this wrapper? Our client app has been using the much outdated SharpAuthorize wrapper and we're looking to switch to this SDK, but we were wondering if we should wait for an update first for the changes described in the above article.

Thank you.

**Comment by Reza-Mortazavi** [comment]
Any update on this?

**Comment by cklenk** [comment]
@Reza-Mortazavi  I was wondering the same thing too.

**Comment by chuyinthesand** [comment]
Authorize.Net, we need an update on this,

**Comment by chsriniv9** [comment]
All, 

We are working on releasing an updated SDK and will communicate on the same in couple of days. 

Please keep watching the space - [MD5 Hash End of Life & Signature Key Replacement](https://support.authorize.net/s/article/MD5-Hash-End-of-Life-Signature-Key-Replacement)

Stay Tuned!!

**Comment by kylepauljohnson** [comment]
Has this been released yet?  Additionally are you going to release this for the .net core beta repo?  Seems your cutting it close for folks here.

**Comment by skyleraustin** [comment]
Any update?

**Comment by chsriniv9** [comment]
@sebastians86 @Reza-Mortazavi @cklenk @chuyinthesand @kylepauljohnson 

We have released updated version of SDK removing older methods. Please refer to - [sdk-dotnet v2.0.0](https://github.com/AuthorizeNet/sdk-dotnet/releases/tag/2.0.0)

Please feel free to re-open the issue if you need any further support.

Thanks

**Comment by yehuda-alon** [comment]
Does version 2.0.0 no longer use MD5?

**Comment by chuyinthesand** [comment]
Hi, we are currently using 1.9.4 on 30+ production sites and cannot simply update to a new version. Will we be able to test our current version / code against the Sandbox today (3/7) to see if / where we are impacted? Will 1.9.4 no longer work on 3/28?

We need a lot more information than "new version released". And, if current versions are impacted by 3/28, well that is just unacceptable.

Thanks in advance!

**Comment by chsriniv9** [comment]
@yehuda-alon 
As per the official [announcement](https://support.authorize.net/s/article/MD5-Hash-End-of-Life-Signature-Key-Replacement), transHash (which uses MD5 based hashing) will be deprecated and to continue verifying via hash, this will require applications to support the SHA-512 hash via signature key.

The  SDK v2.0.0 is verified for empty value for transHash (which is deprecated) and actual value for transHashSha2 sent in response.

To perform verification on this field, we have provided a [sample code](https://github.com/AuthorizeNet/sample-code-csharp/blob/master/Sha512/ComputeTransHashSHA2.cs ) for reference.

For Sandbox and Prod dates for MD5 hash EoL, please keep watching the space - [MD5 Hash End of Life & Signature Key Replacement](https://support.authorize.net/s/article/MD5-Hash-End-of-Life-Signature-Key-Replacement)

**Comment by chsriniv9** [comment]
> Hi, we are currently using 1.9.4 on 30+ production sites and cannot simply update to a new version. Will we be able to test our current version / code against the Sandbox today (3/7) to see if / where we are impacted? Will 1.9.4 no longer work on 3/28?
> 
> We need a lot more information than "new version released". And, if current versions are impacted by 3/28, well that is just unacceptable.
> 
> Thanks in advance!

As per MD5 hash EoL date announcement for sandbox, one should be able to test the sdks (older & latest) against it from that day.

There is advance deprecation message on older methods as part of Oct 18 release of [sdk-dotnet v1.9.6](https://github.com/AuthorizeNet/sdk-dotnet/releases/tag/1.9.6).

**Comment by chsriniv9** [comment]
> Has this been released yet? Additionally are you going to release this for the .net core beta repo? Seems your cutting it close for folks here.

>
No changes to .net core beta released earlier with respect to MD5 hash EoL.
