### ISSUE TITLE
paymentMethodsTypeEnum.AndroidPay should be renamed to GooglePay

### ISSUE THREAD

**Issue by DrewNull** [AuthorizeNet/sdk-dotnet#267]
We are seeing a production and sandbox issue, since the evening of Monday 6/17, in which calls to `getMerchantDetailsRequest` are failing to deserialize the XML response due to a mismatch in `paymentMethodsTypeEnum` enum. 

The SDK currently has `AndroidPay` as a value in the enum, but the `getMerchantDetailsRequest` now returns a value of `GooglePay` instead. 

So, the following `AndroidPay` should be replaced with `GooglePay`: 
https://github.com/AuthorizeNet/sdk-dotnet/blob/8fba3d1149f81b9c78c4b722ef0b74b49777ff56/Authorize.NET/Api/Contracts/V1/AnetApiSchema.generated.cs#L6452

Here is a developer forum thread with the same issue:
https://community.developer.authorize.net/t5/Integration-and-Testing/Request-Get-Merchant-Details-is-not-working-in-Sandbox/m-p/68033/highlight/true#M41316

Thanks

**Comment by linman0x90** [comment]
We experiencing the same issue in a mission critical application.

**Comment by gnongsie** [comment]
Hi,
We are aware of issues to this API. We are currently working to resolve this. A fix has already been identified and will be available on Friday.

Apologies for the inconvenience.

**Comment by gnongsie** [comment]
Hi,
Our tests for this issue have passed. Travis CI builds have also turned green.
Can you validate if you are still seeing this issue?

**Comment by DrewNull** [comment]
Nope--This appears to be cleared up now. Thanks
