### ISSUE TITLE
Allow ValidationMode for AddCreditCard

### ISSUE THREAD

**Issue by tig4647** [AuthorizeNet/sdk-dotnet#29]
Because we do not want to validate by charging the customer to create a payment profile, it would be beneficial to be able to set this.
I changed it on my local as below:

   public string AddCreditCard(string profileID, string cardNumber, int expirationMonth, int expirationYear, string cardCode, Address billToAddress,validationModeEnum validationMode) {

            // Get the expiration date.

            DateTime dt; // = DateTime.Parse(expirationMonth.ToString() + "-1-" + expirationYear.ToString());
            if (!CommonFunctions.ParseDateTime(expirationYear, expirationMonth, 1, out dt))
            { throw new Exception("Invalid credit card expiration date"); }

            DateTime expDate = new DateTime(dt.Year, dt.Month, 1).AddMonths(1).AddDays(-1);
            string sExpDate = expDate.ToString("yyyy-MM");
            // Make sure the card has not expired.
            if (expDate <= DateTime.Now)
                throw new Exception("The credit card expiration date \"" + sExpDate + "\" is expired.");

            var req = new createCustomerPaymentProfileRequest();
            

            req.customerProfileId = profileID;
            req.paymentProfile = new customerPaymentProfileType();
            req.paymentProfile.payment = new paymentType();
            req.validationMode=validationMode;
            req.validationModeSpecified=true;
            var card = new creditCardType();
            if (!String.IsNullOrEmpty(cardCode)) card.cardCode = cardCode;
            card.cardNumber = cardNumber;
            card.expirationDate = sExpDate;
            req.paymentProfile.payment.Item = card;

            if (billToAddress != null)
                req.paymentProfile.billTo = billToAddress.ToAPIType();

            req.validationModeSpecified = true;
            req.validationMode = this._mode;

            var response = (createCustomerPaymentProfileResponse)_gateway.Send(req);
            
            return response.customerPaymentProfileId;
        }

**Comment by brianmc** [comment]
Hi Jason, 
You're right this is an omission in the current PaymentProfile request object.  I know we've pointed you at new model before for other issues so I hope you don't think we're passing the buck but if you use the new controller model you should see that the CustomerPaymentProfileRequest object has validationMode enum included.

BTW We'll soon be releasing a new bank of sample C# code for all our functionality using the new model.
Give me a shout if you don't agree with closing this one out.

Thanks,

BRian
