### ISSUE TITLE
Strong Name Assembly

### ISSUE THREAD

**Issue by pimpalize** [AuthorizeNet/sdk-dotnet#43]
Is there anyway that you can give a strong name to the AuthorizeNet.dll assembly that is officially released? I pull it down from NuGet as new versions are released and I cannot give any assemblies that use it a strong name.

**Comment by kevinfairchild** [comment]
@brianmc, I know this is an old request but I was looking for a strong named library as well.

What are your thoughts on including a SN'ed assembly and a non-SN'ed assembly the release? The non-SN'ed version would allow existing integrations to work the same as always, while the SN'ed version would be available for any who want it.

Just a thought...

**Comment by oddmanted** [comment]
Is there any update on this issue?
We would like to use a Strong Named assembly through nuget package.
Since all our application components are signed with Strong Name, incorporation of Authorize.Net is throwing errors.

**Comment by Externaluse** [comment]
This is related to #179 from 2017; whereas this topic started in 2014 - still nothing new?

**Comment by gnongsie** [comment]
This has been released as part of v1.9.6. I'll be closing this issue now.
