### ISSUE TITLE
Environment class Poorly Named

### ISSUE THREAD

**Issue by MikeLooper** [AuthorizeNet/sdk-dotnet#45]
The new Environment (Environment.cs) class causes collisions with the System.Environment class, with the result that references to either class must be fully defined.
Change class name to something that does not cause collisions.

**Comment by chsriniv9** [comment]
@MikeLooper please try the step as suggested by @bojake. Let us know if that address the issue reported or need further assistance.

**Comment by chsriniv9** [comment]
Closing this assuming the steps provided previously had helped in resolving the issue. Please feel free to re-open if you need any further support.
