### ISSUE TITLE
some GatewayResponse values are wrong if Order.Description contains a comma

### ISSUE THREAD

**Issue by mrmoses** [AuthorizeNet/sdk-dotnet#49]
Here's my specific use case:
```c#
decimal amount = 159m;
orderDesc = "Some text, with a comma";
AuthorizeNet.Order order = new AuthorizeNet.Order(profileId, paymentProfileId, shippingAddress)
{
    Amount = amount,
    Description = orderDesc
};

IGatewayResponse authorizeNetResp  = customerGateway.AuthorizeAndCapture(order);

// authorizeNetResp.Amount is 0 but should be 159
```

This is probably happening in a lot of scenarios (if address or shipping fields contain commas) because the response contains those fields, and just does a `.Split(",")` to parse out all the values. If the request has a description (or address or shipping field) that contains a comma, all the values after that in the response are messed up.

As a workaround for now, I am just removing commas from the description.

**Comment by brianmc** [comment]
This is a very valid issue thank-you for reporting.  However I'm closing this as we are moving away from using CustomerGateway to do charges and a future release of this SDK will integrate with createTransaction for a much more standardized payment transaction flow (no DirectResponse parsing).  http://developer.authorize.net/api/reference/index.html#payment-transactions-charge-a-customer-profile

You can also use this feature today with our new controller model an example is :    https://github.com/AuthorizeNet/sdk-dotnet/blob/master/AuthorizeNETtest/Api/Controllers/SampleTest/CreateTransactionSampleTest.cs
