### ISSUE TITLE
HttpXmlUtility.Send() is not thread-safe.

### ISSUE THREAD

**Issue by RobARichardson** [AuthorizeNet/sdk-dotnet#51]
Because _xmlDoc is a class-level variable, HttpXmlUtility.Send() is not thread-safe.  As an example, if I attempt to call ReportingGateway.GetTransactionDetails in parallel for multiple transaction Ids, I get strange behavior like null reference exceptions because multiple threads are using the same XmlDocument instance.  Would suggest moving _xmlDoc inside the 'Send' method.

**Comment by RobARichardson** [comment]
Really bummed to see that this fix didn't make it into the latest release (1.8.4).  What gives?

**Comment by akankaria** [comment]
We have made the changes for fixing this issue in the latest release 1.9.0. Thanks for raising the issue.
