### ISSUE TITLE
Amounts are converted to string using enviroment culture. But invariant culture should be used

### ISSUE THREAD

**Issue by pauliusg** [AuthorizeNet/sdk-dotnet#59]
for example in CardPresentPriorAuthCapture.cs file (and in many other places) there is a code line:
this.Queue(ApiFields.Amount, amount.ToString());

So, if in your environment decimal separator is ",", then decimal 5.5M is converted to string "5,5".

it should be: 
this.Queue(ApiFields.Amount, amount.ToString(CultureInfo.InvariantCulture));

Because in AIM_guide.pdf documentation field x_amount description says:
Value: Amount of the transaction.
Format: 15 digit-maximum, with a decimal point (no dollar symbol). For
example, 8.95.
Notes: This is the total amount and must include tax, shipping, and any
other charges.

**Comment by ramittal** [comment]
Thanks for reporting the issue. While we investigate the issue, you should be able to use the apis from our new controller model.
We recently added new controller model with all the existing ability to create standard CreateTransaction with some new features, that does not involve any parsing of the request/responses. I recommend you to try that out. Here is a sample test code that you can take a look on usage of the new model: 
https://github.com/AuthorizeNet/sdk-dotnet/blob/master/AuthorizeNETtest/Api/Controllers/SampleTest/CreateTransactionSampleTest.cs
Hope this helps.

**Comment by pauliusg** [comment]
Thanks for response, yesterday I did quick fix in my code:

...
            var gate = new Gateway(configuration.ApiLoginId, configuration.TransactionKey, configuration.IsTestMode);

            var request = new CardPresentAuthorizationRequest(amount, cardAndBillingInfo.CardNumber, cardAndBillingInfo.CardExpirationMonth, cardAndBillingInfo.CardExpirationYear);
            request.Amount = amount.ToString(CultureInfo.InvariantCulture); //NOTE: fixed to invariant culture
...

So it is working in my code. But thanks for your suggestion, maybe I will use your new code.

**Comment by mathieukempe** [comment]
+1

**Comment by ramittal** [comment]
This has been addressed in the development branch (future) https://github.com/AuthorizeNet/sdk-dotnet/commit/3526a577cdf0c53e9b93f9e1b3ba1755f6306164. The next SDK release would have the fix. Thanks for identifying and reporting the issue.

**Comment by brianmc** [comment]
Fix included in latest release 1.8.4
