### ISSUE TITLE
Illegal child notes when rendering profileTransAuthCapture via CIM

### ISSUE THREAD

**Issue by lorddev** [AuthorizeNet/sdk-dotnet#76]
STR:

            var gateway = new CustomerGateway(_apiLogin, _transactionKey, _serviceMode);

            var order = new Order(_customerProfileId, _paymentProfileId, null)
            {
                Amount = amount,
                Description = placeholder
            };

            IGatewayResponse response = null;
            
            switch (_authType)
            {
                case "AUTH_CAPTURE":
                    response = gateway.AuthorizeAndCapture(order);
                    break;
                default:
                    throw new NotImplementedException("derp.");
            }

Result:

> "exceptionMessage": "Error processing request: E00003 - The element 'profileTransAuthCapture' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd' has invalid child element 'customerPaymentProfileId' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd'. List of possible elements expected: 'tax, shipping, duty, lineItems, customerProfileId' in namespace 'AnetApi/xml/v1/schema/AnetApiSchema.xsd'.",

**Comment by lorddev** [comment]
Solution was to use the profileTransAuthOnly element and add x_type=AUTH_CAPTURE in the "extraOptions" node. There seriously is no other way to do it without fixing the server-side code. I will issue a merge request soon.

**Comment by lorddev** [comment]
Nevermind. That didn't work. It just started giving the same message for profileTransAuthOnly. Going to have to roll my own classes to call the API via JSON.

**Comment by ramittal** [comment]
Thanks for reporting the issue. While we investigate the issue, you should be able to use the apis from our new controller model. Have you tried using the new controller model for what you are trying to do?

We recently added new controller model with all the existing ability to create standard CreateTransaction with some new features, that does not involve any parsing of the request/responses. I recommend you to try that out. Here is a sample test code that you can take a look on usage of the new model: 
https://github.com/AuthorizeNet/sdk-dotnet/blob/master/AuthorizeNETtest/Api/Controllers/SampleTest/CreateTransactionSampleTest.cs
Hope this helps.

**Comment by lorddev** [comment]
@ramittal As far as I can tell, the controllers use the same serializers as CustomerGateway. I just chose to roll my own API via JSON serialization with the help of anonymous types and Json.NET.

**Comment by brianmc** [comment]
Hi @lorddev   The standard createTransaction method is definitely the way to go for charging profiles going forward.  Here's the sample from our API Reference http://developer.authorize.net/api/reference/index.html#payment-transactions-charge-a-customer-profile

We have a few minor updates to this method still outstanding and then we'll be deprecating the CIM Gateway method http://developer.authorize.net/api/reference/index.html#charge-customer-profiles

Let me know if you're not ok with closing this issue based on this approach.
