### ISSUE TITLE
Invalid values returned from AuthorizeAndCapture (Test)

### ISSUE THREAD

**Issue by ZombiesWithCoffee** [AuthorizeNet/sdk-dotnet#78]
In test mode (and could be production), the AuthorizeAndCapture method of CIM returns null/0 for all properties.  I would assume that it isn't parsing the returned data correctly.  A valid transaction returns Approved = false and AuthorizationCode/Amount to null.

                var response = gateway.AuthorizeAndCapture(order);

                if (!response.Approved){
                    throw new AuthorizeNetException("The transaction was not approved.");
                }

                var payment = new Payment{
                    DateTime = DateTime.Now,
                    Type = PaymentType.CreditCard,
                    AuthorizationCode = response.AuthorizationCode,
                    Amount = response.Amount
                };

response.ResponseCode = "OkI00001Successful."
response.Approved = false
response.CAVResponse = "Blank or not present = CAVV not validated"

**Comment by andoband** [comment]
I'm seeing this too, and it's preventing me from using this library.

**Comment by ZombiesWithCoffee** [comment]
They've fixed the problem, but haven't done a release yet so you can't use NuGet to update it.

For now, download the entire SDK, compile it, and add it as a reference.

**Comment by ramittal** [comment]
Thanks for reporting the issue. The fix was made in the future branch https://github.com/AuthorizeNet/sdk-dotnet/commit/fcec6e879d82fa901846ac4a349b772d518cad49 and will be included in the next release.

**Comment by brianmc** [comment]
Fix included in latest release 1.8.4
