### ISSUE TITLE
Update Urls for Authorize.NET

### ISSUE THREAD

**Issue by kashyapus** [AuthorizeNet/sdk-dotnet#87]
Yesterday received the announcement from Authorize.NET that they are changing the Url to use Akamai based urls as mentioned below.

*	https://api2.authorize.net/xml/v1/request.api
*	https://api2.authorize.net/soap/v1/Service.asmx
*	https://secure2.authorize.net/gateway/transact.dll

Can you update the Environment file to point to new url or create a switch so that we can use the new url?

**Comment by CuriousLayman** [comment]
+1

**Comment by jasjar** [comment]
+1

**Comment by rmuralidharan** [comment]
+1

**Comment by brianmc** [comment]
This update is coming soon, I do want to assure you that the current URLs are working and will continue to work.

Thanks,

Brian

**Comment by kashyapus** [comment]
I don't understand then the premise of the change (in urls) if the SDK thinking is taking this as after thought. I would think they would do it immediately after the urls went live. 

If you are providing new capabilities and its not part of SDK what's the use of it? I am not sure how many people are using hand crafted api integration.

**Comment by brianmc** [comment]
New version 1.8.5 is released https://github.com/AuthorizeNet/sdk-dotnet/releases/tag/1.8.5 and available on NuGet.
