### ISSUE TITLE
ARB GetListOFSubscriptions needs to be supported

### ISSUE THREAD

**Issue by sckid1108** [AuthorizeNet/sdk-dotnet#88]
see docs here
http://developer.authorize.net/api/reference/index.html#recurring-billing-get-a-list-of-subscriptions

Have some code that implements the functionality, let me know if you want it.  Dont seem to have the permissions to update a branch here

**Comment by brianmc** [comment]
Hi @sckid1108, GetSubscriptionsList is supported in the new model and you can find sample code here : https://github.com/AuthorizeNet/sdk-dotnet/blob/master/AuthorizeNETtest/Api/Controllers/SampleTest/ArbSubscriptionSampleTest.cs

Hope this helps,

Brian
