### ISSUE TITLE
Free Trial is not possible

### ISSUE THREAD

**Issue by iamruss** [AuthorizeNet/sdk-dotnet#92]
Hello,

trying to create a free trial using ISubscriptionRequest.SetTrialPeriod method

```
subscription.SetTrialPeriod(1, 0); // the trial amount is zero dollars
```

but I am getting this error
Error processing request: E00026 - Both Trial Amount and Trial Occurrences are required.

The code checks if the TrialAmount is greater than Zero and only then sets ".hasTrialAmount". To workaround this I am doing something like this:

```
subscription.SetTrialPeriod(1, new Decimal(0.0001))
```

and I am not sure if that is a "Free Trial" anyway.

So, my current plan is to set StartDate to the date  _after_ the trial period ends and not use TrialAmount and TrialOccurencies properties at all.

Please advise.

**Comment by bsjaffer** [comment]
i am also facing the same issue.

**Comment by bsjaffer** [comment]
seems to be high priority issue, why no response for last 20 days?

**Comment by brianmc** [comment]
Hi there,

We are looking at this issue but in the meantime you can use our new model which will does not have this issue.  One of the big reasons we are moving to a new model in the SDK is to avoid these types of issues in the SDK.  The new model is a very lightweight language binding for the API and as such we are able to reduce logic flaws and keep the SDK in sync with the API much more efficiently.  

Check out this sample in our new sample code repo : https://github.com/AuthorizeNet/sample-code-csharp/blob/master/RecurringBilling/CreateSubscription.cs 

Brian

**Comment by brianmc** [comment]
Hi @bsjaffer @iamruss, Did this help?

Brian

**Comment by brianmc** [comment]
Closing this one.
