### ISSUE TITLE
Method not found

### ISSUE THREAD

**Issue by bsjaffer** [AuthorizeNet/sdk-dotnet#93]
Hi

When I try to use ARB payment and when I call PopulateSubscription, its throwing a error as first value i am set in that function. 

Method not found: 'Void AuthorizeNet.APICore.ARBSubscriptionType.set_name(System.String)'.

Method not found: 'Void AuthorizeNet.APICore.creditCardSimpleType.set_cardNumber(System.String)'.

Please help. 

Thanks,
Jaffer

**Comment by bsjaffer** [comment]
Code snipet.

  ARBSubscriptionType sub = new ARBSubscriptionType();
                creditCardType creditCard = new creditCardType();


  sub.name = recurringitem.Product.Sku;

   creditCard.cardNumber = cardnumber;
                creditCard.expirationDate = expyear + "-" + expMonth;
                sub.payment = new paymentType();
                sub.payment.Item = creditCard;

**Comment by brianmc** [comment]
Try our controller model, here's a sample for CreateSubscription https://github.com/AuthorizeNet/sample-code-csharp/blob/master/RecurringBilling/CreateSubscription.cs 

It's a thin C# wrapper on our API and so it's very easy to reconcile between them for troubleshooting.  Here's the API reference:  http://developer.authorize.net/api/reference/#recurring-billing-create-a-subscription
