### ISSUE TITLE
CIM AuthorizeAndCapture(order) succeeds but almost all response fields are empty, including TransactionID

### ISSUE THREAD

**Issue by TomWHall** [AuthorizeNet/sdk-dotnet#96]
Hi, I'm using the CIM. I'm using the overload of AuthorizeAndCapture which accepts an Order. It succeeds and I can see the captured transaction in the Authorize.Net portal. However, the response object that I get back has barely any properties set. The ResponseCode string contains all of the values I would expect, i.e. the correct TransactionID, the string "This transaction has been approved.", etc. But it is not in a robust form to work with. The TransactionID property of the response is an empty string, Approved is false, and almost everything else is an empty string. What is going on?

**Comment by brianmc** [comment]
Hi Tom, we're looking into this.  In the meantime you may want to check out a sample of charging a CIM profile using our new model:  https://github.com/AuthorizeNet/sample-code-csharp/blob/master/PaymentTransactions/ChargeCustomerProfile.cs  

This method uses the same API call as our standard CreateTransaction and the new model is a much lighter binding over our API.

You can add order information simply by newing up an OrderType and adding it to the transactionRequest.

Hope this helps, we'll keep you updated on the CIMGateway investigation,

Brian

**Comment by TomWHall** [comment]
Thanks Brian. In your example I'm unclear on how we would execute a charge against a customer's existing PaymentProfile (credit card) without sending through the card details with the transaction - we only persist ProfileIDs for the Customer and PaymentProfile.

**Comment by brianmc** [comment]
Hi Tom, sorry that sample still uses credit card info, I'll get that updated this evening.  There is also  sample here in the sdk tests:  https://github.com/AuthorizeNet/sdk-dotnet/blob/future/AuthorizeNETtest/Api/Controllers/SampleTest/CreateTransactionSampleTest.cs

Brian

**Comment by ramittal** [comment]
Try from the master branch, if link from future-branch does not work
https://github.com/AuthorizeNet/sdk-dotnet/blob/master/AuthorizeNETtest/Api/Controllers/SampleTest/CreateTransactionSampleTest.cs
Look for method: SampleCodeCreateTransactionUsingProfile()

**Comment by brianmc** [comment]
Exactly, updated comment.  Thanks!

**Comment by TomWHall** [comment]
Great, that worked. Thank you very much. We are going live with this in a few weeks, is this newer model likely to be changing much anytime soon?

**Comment by TomWHall** [comment]
Also - when using the CIM to charge existing customers (via the old or new model), is it compulsory to always have a billing address against the payment profile? If I don't supply an address I get "missing or invalid fields" when I try to add the credit card, even with the AVS filter disabled and no address fields marked as required.

**Comment by brianmc** [comment]
No it shouldn't be compulsory for US processors.  You can try this out using the API Explorer, that takes any client code issues away at least for testing:
1.  Create a profile here (Try It payload has no address) : http://developer.authorize.net/api/reference/#manage-customer-profiles-create-customer-profile
2.  Charge that new profile here : http://developer.authorize.net/api/reference/#payment-transactions-charge-a-customer-profile

BTW New updated sample for charging a profile is here:  https://github.com/AuthorizeNet/sample-code-csharp/blob/master/PaymentTransactions/ChargeCustomerProfile.cs

**Comment by brianmc** [comment]
New model is the go-forward model for the SDKs, we don't plan to change that any time soon.
