### ISSUE TITLE
[CIM] AuthorizeNet.CustomerGateway.ValidateProfile() fails for ServiceMode.Test

### ISSUE THREAD

**Issue by amtgard** [AuthorizeNet/sdk-dotnet#97]
Steps:
Instantiate CustomerGateway with ServiceMode.Test
Call ValidateProfile()

Results:
Throws error E00013, invalid field (wrong validation mode set).

The issue is that CustomerGateway sets validation mode = test when ServiceMode = test (CIM/CustomerGateway.cs lines 25 - 30); however, validation modes are separate from service modes.  

In this case, validateCustomerPaymentProfileRequest requires that the validation mode be set to "Live" regardless of the ServiceMode (ie, sandbox vs production).

One solution is to expose a setter for CustomerGateway._mode, so that it can be set on a per-call basis.  Alternately, add parameters to ValidateProfile(), or have ValidateProfile() temporarily set the validation mode to Live if the ServiceMode is test.

**Comment by brianmc** [comment]
Hi @amtgard,  Have you tried the new controllers available in the SDKs?   They provide a much "closer-to-api" experience and therefore there's less logic in the SDK that could either be incorrect or have become invalid as the API/server business logic changes.   Here's a full sample for validating a profile:   https://github.com/AuthorizeNet/sample-code-csharp/blob/master/CustomerProfiles/ValidateCustomerPaymentProfile.cs

Let us know what you think,

Brian

**Comment by brianmc** [comment]
Closing this due to new model support.  Please let us know if you have any additional feedback.
